/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Others.MyTableCellRenderer;
import BUS.nhaXuatBanBUS;
import DTO.sachDTO;
import DAO.sachDAO;
import BUS.sachBUS;
import BUS.tacgiaBUS;
import BUS.theLoaiiBUS;
import DAO.tacGiaDAO;
import DAO.theLoaiDAO;
import DTO.nhaXuatBanDTO;
import DTO.tacGiaDTO;
import DTO.theLoaiDTO;
import Others.MyFileChooser;
import Others.XuLyFileExcel;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;


/**
 *
 * @author ADMIN
 */
public class JPnBooks extends javax.swing.JPanel {
DefaultTableModel dtmsach = new DefaultTableModel();
DefaultTableModel dtmsearch = new DefaultTableModel();

ArrayList<sachDTO> listSach = new ArrayList<>();

    /**
     * Creates new form JPnBooks
     */
    public JPnBooks() {
        initComponents();
        JTableHeader header = tblSach.getTableHeader();
        dtmsach = (DefaultTableModel) tblSach.getModel();
        dtm1 = (DefaultTableModel) tblTheloai.getModel();
        dtmsearch = (DefaultTableModel) tblSach.getModel();
        header.setOpaque(false);
        tblSach.setRowHeight(25);
        loadDataLenBangSanPham();
   //     loadDataCmbTacgia();
        loadtbltacgia();
        loadDataCmbMaTheLoai();
        loadDataCmbMatacgia();
        loadtbltheloai();
               tblSach.setDefaultRenderer(Object.class, new MyTableCellRenderer(8));
         searchLive();

    }
    theLoaiiBUS theloai_bus = new theLoaiiBUS();
    sachBUS sach_bus = new sachBUS();

    tacgiaBUS tgbus = new tacgiaBUS();
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtnam = new javax.swing.JTextField();
        lbanh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnChoose = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        cmbtheloai = new javax.swing.JComboBox();
        cmbtacgia = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttentl = new javax.swing.JTextField();
        txtmatl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheloai = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtgttg = new javax.swing.JTextField();
        txtmatg1 = new javax.swing.JTextField();
        txttentg = new javax.swing.JTextField();
        btnXoatg = new javax.swing.JButton();
        btnSuatg = new javax.swing.JButton();
        btnThemtg2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTacgia = new javax.swing.JTable();

        setBackground(new java.awt.Color(130, 195, 65));
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setPreferredSize(new java.awt.Dimension(1000, 649));

        jTabbedPane1.setBackground(new java.awt.Color(130, 195, 65));

        jPanel1.setBackground(new java.awt.Color(130, 195, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 649));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSach.setForeground(new java.awt.Color(0, 0, 0));
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Mã tác giả", "Mã thể loại", "Năm sản xuất", "Số lượng", "Ảnh", "Giá", "Trạng thái"
            }
        ));
        tblSach.setToolTipText("");
        tblSach.setGridColor(new java.awt.Color(0, 0, 0));
        tblSach.setRowHeight(25);
        tblSach.setSelectionBackground(new java.awt.Color(130, 195, 65));
        tblSach.setShowHorizontalLines(true);
        tblSach.setShowVerticalLines(true);
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 286, 1000, 363));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý sách");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã sách");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên sách");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tác giả");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Năm sản xuất");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        txtma.setEditable(false);
        txtma.setBackground(new java.awt.Color(204, 204, 204));
        txtma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaKeyPressed(evt);
            }
        });
        jPanel1.add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, -1));
        jPanel1.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 230, -1));
        jPanel1.add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 230, -1));

        lbanh.setForeground(new java.awt.Color(255, 255, 255));
        lbanh.setToolTipText("");
        lbanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbanh.setMinimumSize(new java.awt.Dimension(200, 200));
        lbanh.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(lbanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 200, 200));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ảnh");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 250, -1));

        btnRemove.setBackground(new java.awt.Color(213, 214, 217));
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Delete.png")); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, 30));

        btnExport.setBackground(new java.awt.Color(213, 214, 217));
        btnExport.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Microsoft Excel.png")); // NOI18N
        btnExport.setText("Xuất Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jPanel1.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, 30));

        btnImport.setBackground(new java.awt.Color(213, 214, 217));
        btnImport.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Microsoft Excel.png")); // NOI18N
        btnImport.setText("Nhập Excel");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel1.add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 30));

        btnChoose.setLabel("Chọn ảnh");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        jPanel1.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, 30));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Thể loại");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cmbtheloai.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmbtheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, -1));

        cmbtacgia.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmbtacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tìm kiếm");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 30));

        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });
        jPanel1.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 330, -1));

        jTabbedPane1.addTab("Sách", jPanel1);

        jPanel2.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quản lý thể loại");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tên thể loại");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, 30));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Mã thể loại");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 100, 30));
        jPanel2.add(txttentl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 320, 30));

        txtmatl.setEditable(false);
        txtmatl.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.add(txtmatl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 320, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Delete.png")); // NOI18N
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 110, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 110, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Edit.png")); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, 30));

        tblTheloai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã TL", "Tên TL"
            }
        ));
        tblTheloai.setShowVerticalLines(true);
        tblTheloai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheloaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTheloai);
        if (tblTheloai.getColumnModel().getColumnCount() > 0) {
            tblTheloai.getColumnModel().getColumn(0).setMinWidth(30);
            tblTheloai.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblTheloai.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 960, 210));

        jTabbedPane1.addTab("Thể loại", jPanel2);

        jPanel3.setBackground(new java.awt.Color(130, 195, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Quản lý tác giả");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 23, 1000, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Giới tính tác giả");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mã tác giả");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tên tác giả");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        jPanel3.add(txtgttg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 310, -1));

        txtmatg1.setEditable(false);
        txtmatg1.setBackground(new java.awt.Color(130, 195, 65));
        jPanel3.add(txtmatg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 310, -1));
        jPanel3.add(txttentg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 310, -1));

        btnXoatg.setBackground(new java.awt.Color(255, 255, 255));
        btnXoatg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Delete.png")); // NOI18N
        btnXoatg.setText("Xóa");
        btnXoatg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoatgActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoatg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 110, 30));

        btnSuatg.setBackground(new java.awt.Color(255, 255, 255));
        btnSuatg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Edit.png")); // NOI18N
        btnSuatg.setText("Sửa");
        btnSuatg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuatgActionPerformed(evt);
            }
        });
        jPanel3.add(btnSuatg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, 30));

        btnThemtg2.setBackground(new java.awt.Color(255, 255, 255));
        btnThemtg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        btnThemtg2.setText("Thêm");
        btnThemtg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemtg2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemtg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 110, 30));

        tblTacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã tác giả", "Tên tác giả", "Giới tính"
            }
        ));
        tblTacgia.setOpaque(false);
        tblTacgia.setRowHeight(25);
        tblTacgia.setShowHorizontalLines(true);
        tblTacgia.setShowVerticalLines(true);
        tblTacgia.setSurrendersFocusOnKeystroke(true);
        tblTacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacgiaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTacgia);
        if (tblTacgia.getColumnModel().getColumnCount() > 0) {
            tblTacgia.getColumnModel().getColumn(0).setMinWidth(30);
            tblTacgia.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblTacgia.getColumnModel().getColumn(0).setMaxWidth(100);
            tblTacgia.getColumnModel().getColumn(2).setMinWidth(30);
            tblTacgia.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblTacgia.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 960, 300));

        jTabbedPane1.addTab("Tác giả", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void luuAnhFile() {
        BufferedImage bImage = null;
        try {
            File initialImage = new File(fileAnhSach.getPath());
            bImage = ImageIO.read(initialImage);
            ImageIO.write(bImage, "png", new File("image/book/" + fileAnhSach.getName()));
        } catch (IOException e) {

        }

    }
    private void tblTacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacgiaMouseClicked
        // TODO add your handling code here:
         int i = tblTacgia.getSelectedRow();

     txtmatg1.setText(tableModel.getValueAt(i,0).toString());
    // txthotg.setText(tableModel.getValueAt(i,1).toString());
     txttentg.setText(tableModel.getValueAt(i,1).toString());
     txtgttg.setText(tableModel.getValueAt(i, 2).toString());
     
    }//GEN-LAST:event_tblTacgiaMouseClicked

    private void btnThemtg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemtg2ActionPerformed
        // TODO add your handling code here:
        if(txttentg.getText().length()<=0 || txtgttg.getText().length()<=0){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin tác giả");
            return;
        }
        tacGiaDTO tg = new tacGiaDTO();
     //   tg.setHo(txthotg.getText());
        tg.setTen(txttentg.getText());
        tg.setGioiTinh(txtgttg.getText());
        try{
        tgbus.insert_BUS(tg);
        JOptionPane.showMessageDialog(null, "Thêm thành công!");
        }catch(Exception e){ JOptionPane.showMessageDialog(null, "Thêm thất bại!");}
        loadtbltacgia();
    }//GEN-LAST:event_btnThemtg2ActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        xuLyChonAnh();
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        XuLyFileExcel nhapFile = new XuLyFileExcel();
        nhapFile.nhapExcel(tblSach);
        System.out.println("test 685 sach gui");
        int row = tblSach.getRowCount();

        System.out.println("test 685 lan 2 sach gui");
        for (int i = 0; i < row; i++) {
            System.out.println("test 690 ");
            //   String ma = tblSach.getValueAt(i, 1) + "";

            System.out.println("test 693");
            String ten = tblSach.getValueAt(i, 1) + "";
            System.out.println("test 170 sach dao");
            String matacgia = tblSach.getValueAt(i, 2) + "";
            String matheloai = tblSach.getValueAt(i, 3) + "";
            String mansx = tblSach.getValueAt(i, 4) + "";
            String namsx = tblSach.getValueAt(i, 5) + "";
            String soLuog = tblSach.getValueAt(i, 6) + "";
            String Anh = tblSach.getValueAt(i, 7) + "";

            String Gia = tblSach.getValueAt(i, 8) + "";
            System.out.println("test 700 gui");
            sach_bus.nhapSachTuExel( ten, matacgia, matheloai, mansx, namsx, soLuog, Anh, Gia);
        }
        System.out.println("test 700 sach gui-----------");
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        XuLyFileExcel xuatfile = new XuLyFileExcel();
        xuatfile.xuatExcel(tblSach);
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
       if(tblSach.getSelectedRow()<0){
           JOptionPane.showMessageDialog(null,"Vui lòng chọn sách muốn xóa");
           return;
       }
        boolean flag = sach_bus.xoaSanPham(txtma.getText());
        if (flag) {
            loadDataLenBangSanPham();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtma.setEditable(true);
            txtma.setBackground(new Color(255,255,255));

        }
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            txtma.setEditable(false);
            txtma.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtmaKeyPressed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        // TODO add your handling code here:
        int row = tblSach.getSelectedRow();
        if (row > -1) {
            String ma = tblSach.getValueAt(row, 0) + "";
            String Ten = tblSach.getValueAt(row, 1) + "";
            String tacgia = tblSach.getValueAt(row, 2) + "";
            String loai = tblSach.getValueAt(row, 3).toString();

            String namsanxuat = tblSach.getValueAt(row, 4) + "";
            String soluong = tblSach.getValueAt(row, 5) + "";
            String anh = tblSach.getValueAt(row, 6) + "";
            String gia = tblSach.getValueAt(row, 7) + "";
            txtma.setText(ma);
            txtten.setText(Ten);
            //    txttheloai.setText(loai);
            txtnam.setText(namsanxuat);
          ///  txtsl.setText(soluong);
           // txtgia.setText(gia);
            int flag = 0;
                      cmbtacgia.setSelectedItem(tacgia);

            cmbtheloai.setSelectedItem(loai);
            loadAnh("image/book/"+ anh);
        }

    }//GEN-LAST:event_tblSachMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        if(txttentl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Nhập tên thể loại");
            return;
        }
        theLoaiDTO tl = new theLoaiDTO();
        tl.setTen(txttentl.getText());
        Vector header = new Vector();
        header.add("Mã TL");
        header.add("Tên TL");
       try{
        theloai_bus.insert_BUS(tl);
        JOptionPane.showMessageDialog(null, "Thêm thành công!");
        }catch(Exception e){ JOptionPane.showMessageDialog(null, "Thêm thất bại!");}
        loadtbltheloai();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tblTheloai.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn thể loại muốn xóa");
            return;
        }
        theLoaiDTO tl = new theLoaiDTO();
        tl.setMa(Integer.parseInt(txtmatl.getText()));
        tl.setTen(txttentl.getText());
        try{
        theloai_bus.xoaTheLoai(tl.getMa());
        JOptionPane.showMessageDialog(null,"Xóa thành công!");
        }catch(Exception e){        JOptionPane.showMessageDialog(null,"Xóa thất bại!");}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblTheloaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheloaiMouseClicked
        // TODO add your handling code here:
        int i = tblTheloai.getSelectedRow();
        txtmatl.setText(tblTheloai.getValueAt(i,0).toString());
                txttentl.setText(tblTheloai.getValueAt(i,1).toString());

    }//GEN-LAST:event_tblTheloaiMouseClicked

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
        xuLyLiveSearching();
    }//GEN-LAST:event_txttimActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tblTheloai.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn thể loại muốn sửa");
            return;
        }
        String ma = txtmatl.getText();
        String name = txttentl.getText();
        theloai_bus.suaTheLoai(ma, name);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSuatgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuatgActionPerformed
        // TODO add your handling code here:
         if(tblTacgia.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn tác giả muốn sửa");
            return;
        }
        tacGiaDTO tg = new tacGiaDTO();
        tg.setMa(Integer.parseInt(txtmatg1.getText()));
        tg.setTen(txttentg.getText());
        tg.setGioiTinh(txtgttg.getText());
        try{
            tgbus.sua(tg);
            JOptionPane.showMessageDialog(null,"Sửa thành công");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Sửa thất bại");}
    }//GEN-LAST:event_btnSuatgActionPerformed

    private void btnXoatgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoatgActionPerformed
        // TODO add your handling code here:
         if(tblTacgia.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn thể loại muốn xóa");
            return;
        }
         String ma = txtmatg1.getText();
          try{
            tgbus.xoa(Integer.parseInt(ma));
            JOptionPane.showMessageDialog(null,"Xóa thành công");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Xóa thất bại");}
        
    }//GEN-LAST:event_btnXoatgActionPerformed
private void loadAnh(String anh) {
        lbanh.setIcon(getAnhSach(anh));
    }

    private ImageIcon getAnhSach(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        BufferedImage img = null;
        File fileImg = new File(src);
        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/book" + src);
        }
        try {
            img = ImageIO.read(fileImg);
            fileAnhSach = new File(src);

        } catch (IOException e) {

        }
        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);

        }
        return null;

    }

public void loadtblSach(){
    sachDAO dataDAO = new sachDAO();
    dtmsach.setRowCount(0);
       listSach = dataDAO.getListSach();
     Vector header = new Vector();
        header.add("Mã");
        header.add("Tên");
        header.add("Mã tác giả");
        header.add("Mã thể loại");
        header.add("Năm sản xuất");
        header.add("Số lượng");
        header.add("Ảnh");
        header.add("Giá");
        if(dtmsach.getRowCount()==0){
            dtmsach = new DefaultTableModel(header,0);
            
        }
        for (sachDTO s : listSach) {
            Vector vec = new Vector();
            vec.add(s.getMa());
            vec.add(s.getTen());
            vec.add(s.getMaTacGia());
            vec.add(s.getMaTheLoai());
            vec.add(s.getNamSanXuat());
            vec.add(s.getSoLuong());
            vec.add(s.getAnh());
            vec.add(s.getGia());
            
            dtmsach.addRow(vec);
        }
        tblSach.setModel(dtmsach);
           
        }
private void loadDataLenBangSanPham() {
        sach_bus.doclistSach();
        dtmsach.setRowCount(0);

        ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
                vec.add(tgbus.getTentg(sp.getMaTacGia()));
            vec.add(theloai_bus.getTenloai(sp.getMaTheLoai()));

            vec.add(sp.getNamSanXuat());

            vec.add(sp.getSoLuong());
            vec.add(sp.getAnh());
            vec.add(sp.getGia());
            int tt = sp.getTt();
            String trangthai = "";
            if (tt == 1){
                trangthai = "Còn xuất bản";
            }
            else trangthai = "Ngưng xuất bản";
            vec.add(trangthai);
            dtmsach.addRow(vec);
     
        }
    }

 private void loadDataLenBangSanPham( ArrayList<sachDTO> dssp) {
        // sach_bus.doclistSach();
        dtmsearch.setRowCount(0);

       // ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
            vec.add(sp.getMaTacGia());
            vec.add(sp.getMaTheLoai());
            vec.add(sp.getNamSanXuat());
            vec.add(sp.getSoLuong());
            vec.add(sp.getAnh());
            vec.add(sp.getGia());

            dtmsearch.addRow(vec);

        }
    }
 public void loadDataCmbMatacgia (){
        cmbtacgia.removeAll();
        tacgiaBUS tgbus = new tacgiaBUS();
        ArrayList<tacGiaDTO> tacgiaList = tgbus.getDanhSachTacGia();

        cmbtacgia.addItem("0 - chon tac gia ");

        for (tacGiaDTO DataBox : tacgiaList) {
            cmbtacgia.addItem(DataBox.getTen());
        }
        cmbtheloai.addItem("Het");
    }

    public void loadDataCmbMaTheLoai() {
        cmbtheloai.removeAll();
        ArrayList<theLoaiDTO> theloaiList = theloai_bus.getDanhSachLoai();

        cmbtheloai.addItem("0 - chon  the loai ");

        for (theLoaiDTO DataBox : theloaiList) {
            cmbtheloai.addItem(DataBox.getTen());
        }
        cmbtheloai.addItem("Het");
    }

    
        File fileAnhSach;
       public void xuLyChonAnh() {
        JFileChooser fileChooser = new MyFileChooser("image/book/");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp hình ảnh", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileAnhSach = fileChooser.getSelectedFile();
            lbanh.setIcon(getAnhSach(fileAnhSach.getPath()));
        }

    }
           DefaultTableModel tableModel = new DefaultTableModel();
           ArrayList<tacGiaDTO> tgList = new ArrayList<>();

       public void loadtbltacgia(){
    tacGiaDAO dataDAO = new tacGiaDAO();
    tableModel.setRowCount(0);
       tgList = dataDAO.ReadData();
     Vector header = new Vector();
        header.add("Mã tác giả");
   //     header.add("Họ");
        header.add("Tên");
        header.add("Giới tính");
        if(tableModel.getRowCount()==0){
            tableModel = new DefaultTableModel(header,0);
            
        }
        for (tacGiaDTO tg : tgList) {
            Vector vec = new Vector();
            vec.add(tg.getMa());
        //    vec.add(tg.getHo());
            vec.add(tg.getTen());
            vec.add(tg.getGioiTinh());
                      
            tableModel.addRow(vec);
        }
        tblTacgia.setModel(tableModel);
           
        }
       DefaultTableModel dtm1 = new DefaultTableModel();
           ArrayList<theLoaiDTO> tlList = new ArrayList<>();
           
       public void loadtbltheloai(){
            theLoaiDAO dataDAO = new theLoaiDAO();
    dtm1.setRowCount(0);
       tlList = dataDAO.getListTheLoai();
     Vector header = new Vector();
        header.add("Mã thể loại");
   //     header.add("Họ");
        header.add("Tên thể loại");
        //header.add("Giới tính");
        if(tableModel.getRowCount()==0){
            tableModel = new DefaultTableModel(header,0);
            
        }
        for (theLoaiDTO tg : tlList) {
            Vector vec = new Vector();
            vec.add(tg.getMa());
        //    vec.add(tg.getHo());
            vec.add(tg.getTen());
           // vec.add(tg.getGioiTinh());
                      
           dtm1.addRow(vec);
        }
        tblTheloai.setModel(dtm1);
           
       }
           public void trangthaisach(){
         DefaultTableModel md = (DefaultTableModel)tblSach.getModel();
         int i = tblSach.getRowCount();
        
    }
           
            private void xuLyLiveSearching()
    {
        ArrayList<sachDTO> dsSach = sach_bus.timlKiemSachLive(txttim.getText());
        loadDataLenBangSanPham(dsSach);
    }
    public void searchLive()
    {
        txttim.getDocument().addDocumentListener(new DocumentListener()
        {
              @Override
            public void insertUpdate(DocumentEvent e) {
               xuLyLiveSearching();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }   
                
                
                
        } );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btnChoose;
    public javax.swing.JButton btnExport;
    public javax.swing.JButton btnImport;
    public javax.swing.JButton btnRemove;
    public javax.swing.JButton btnSuatg;
    public javax.swing.JButton btnThemtg2;
    public javax.swing.JButton btnXoatg;
    public javax.swing.JComboBox cmbtacgia;
    public javax.swing.JComboBox cmbtheloai;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lbanh;
    public javax.swing.JTable tblSach;
    public javax.swing.JTable tblTacgia;
    public javax.swing.JTable tblTheloai;
    public javax.swing.JTextField txtgttg;
    public javax.swing.JTextField txtma;
    public javax.swing.JTextField txtmatg1;
    public javax.swing.JTextField txtmatl;
    public javax.swing.JTextField txtnam;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txttentg;
    public javax.swing.JTextField txttentl;
    public javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
