/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.ReaderBUS;
import DTO.ReaderDTO;
import DTO.sachDTO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class JPnCustomer extends javax.swing.JPanel {  
       DefaultTableModel dtmkhach = new DefaultTableModel();
       ArrayList<ReaderDTO> listkh = new ArrayList();
       ReaderBUS bus = new ReaderBUS();
    /**
     * Creates new form JPnCustomer
     */
    public JPnCustomer() {
         initComponents();
        dtmkhach = (DefaultTableModel)tblKH.getModel();
       
        loaddataKH();
        searchLive();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txtidkh = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMIn = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKH = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtgt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(130, 195, 65));
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setPreferredSize(new java.awt.Dimension(1000, 649));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý khách hàng");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Địa chỉ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 60, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã khách hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ khách hàng");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 130, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên khách hàng");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giới tính");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 90, 30));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số điện thoại");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, 30));
        add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 200, -1));

        txtidkh.setEditable(false);
        txtidkh.setBackground(new java.awt.Color(130, 195, 65));
        add(txtidkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 200, -1));
        add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 200, -1));
        add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 200, -1));

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Delete.png")); // NOI18N
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 110, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Edit.png")); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 110, 30));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("đến");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 40, 30));
        add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 200, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tìm");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 90, 30));
        add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 440, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Chi tiêu từ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, 30));
        add(txtMIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 200, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tìm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        tblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Họ KH", "Tên KH", "Giới tính", "Địa chỉ", "SĐT", "Tổng chi tiêu"
            }
        ));
        tblKH.setShowVerticalLines(true);
        tblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKH);
        if (tblKH.getColumnModel().getColumnCount() > 0) {
            tblKH.getColumnModel().getColumn(0).setMinWidth(30);
            tblKH.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblKH.getColumnModel().getColumn(0).setMaxWidth(100);
            tblKH.getColumnModel().getColumn(3).setMinWidth(30);
            tblKH.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblKH.getColumnModel().getColumn(3).setMaxWidth(100);
            tblKH.getColumnModel().getColumn(5).setMinWidth(30);
            tblKH.getColumnModel().getColumn(5).setPreferredWidth(70);
            tblKH.getColumnModel().getColumn(5).setMaxWidth(100);
            tblKH.getColumnModel().getColumn(6).setMinWidth(70);
            tblKH.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblKH.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1000, 230));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 760, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 760, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 760, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 10, 202));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 10, 202));
        add(txtgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 200, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Refresh.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         int i = tblKH.getSelectedRow();
             if(i<0){
             JOptionPane.showMessageDialog(null,"Vui lòng chọn khách hàng muốn sửa thông tin");
             return;
         }
        ReaderBUS bus = new ReaderBUS();
        if(i>=0){
            ReaderDTO rd = new ReaderDTO();
     //   rd.id = txtidkh.getText();
        rd.ho = txtho.getText();
        rd.ten = txtten.getText();
       // rd.ngaysinh = dateFormat.format(dob1.getDate());
        rd.gioitinh = txtgt.getText();
        rd.diachi = txtdiachi.getText();
        rd.sdt = Integer.parseInt(txtsdt.getText());
        
            dtmkhach.setValueAt(rd.id,i,0);
            dtmkhach.setValueAt(rd.ho,i,1);
            dtmkhach.setValueAt(rd.ten,i,2);
           // dtmkhach.setValueAt(rd.ngaysinh,i,3);
            dtmkhach.setValueAt(rd.gioitinh, i, 3);
            dtmkhach.setValueAt(rd.diachi,i,4);
            dtmkhach.setValueAt(rd.sdt,i,5);
            tblKH.setModel(dtmkhach);
        bus.sua(rd);
            JOptionPane.showMessageDialog(null,"Edit Successfully.");
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtten.getText().length()<=0 || txtho.getText().length()<=0 || txtgt.getText().length()<= 0 || txtdiachi.getText().length()<= 0 || txtsdt.getText().length()<= 0){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin");
            return;
        }
        ReaderDTO r = new ReaderDTO();
        //r.setid(Integer.parseInt(txtidkh.getText()));
        r.setho(txtho.getText());
        r.setten(txtten.getText());
        r.setgioitinh(txtgt.getText());
        r.setSdt(Integer.parseInt(txtsdt.getText()));
        r.setDiachi(txtdiachi.getText());
        r.setTongct(0);
        bus.khoitao(r, dtmkhach, tblKH);
        loaddataKH();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = tblKH.getSelectedRow();
            if(i<0){
             JOptionPane.showMessageDialog(null,"Vui lòng chọn nhân viên muốn xóa");
             return;
         }
        if(i>=0){
            try {
            String ma = tblKH.getModel().getValueAt(i,0).toString();
            
            listkh.remove(bus.timkiemtheoMa(ma));
            bus.xoa(ma);
            dtmkhach.removeRow(i);
            tblKH.setModel(dtmkhach);
            JOptionPane.showMessageDialog(null,"Delete Successfully.");
        
        }catch (Exception e){
                            JOptionPane.showMessageDialog(null,"Delete Failed.");

                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKHMouseClicked
        // TODO add your handling code here:
        int i = tblKH.getSelectedRow();
        try{
     txtidkh.setText(dtmkhach.getValueAt(i,0).toString());
     txtho.setText(dtmkhach.getValueAt(i,1).toString());
     txtten.setText(dtmkhach.getValueAt(i,2).toString());
     txtgt.setText(dtmkhach.getValueAt(i,3).toString());
     txtdiachi.setText(dtmkhach.getValueAt(i,4).toString());
     txtsdt.setText(dtmkhach.getValueAt(i,5).toString());
        }catch(Exception e){System.out.println(e.toString());}
    }//GEN-LAST:event_tblKHMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(txtMIn.getText().trim().equals("") || txtMax.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập khoảng chi tiêu cần tìm");
            return;
        }
                ArrayList<ReaderDTO> dskh = bus.timKiemKhachHang(txtMIn.getText(), txtMax.getText());
                if(dskh ==null){
                    return;
                }
                loaddataKH(dskh);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loaddataKH();
    }//GEN-LAST:event_jButton5ActionPerformed

     private void loaddataKH(ArrayList<ReaderDTO> dskh) {
        dtmkhach.setRowCount(0);
        DecimalFormat dcf = new DecimalFormat("###,###");
        for (ReaderDTO kh : dskh) {
            Vector vec = new Vector();
            vec.add(kh.getid());
            vec.add(kh.getho());
            vec.add(kh.getten());
            vec.add(kh.getgioitinh());
            vec.add(kh.getDiachi());
            vec.add(kh.getSdt());
            vec.add(dcf.format(kh.getTongct()));
            dtmkhach.addRow(vec);
        }
    }

    private void loaddataKH(){
        bus.doclistKH();
        dtmkhach.setRowCount(0);
        ArrayList<ReaderDTO> ds = bus.getListKH();
         for (ReaderDTO sp : ds) {
            Vector vec = new Vector();
            vec.add(sp.getid());
            vec.add(sp.getho());
            vec.add(sp.getten());
            vec.add(sp.getDiachi());
            vec.add(sp.getgioitinh());
            vec.add(sp.getSdt());
            vec.add(sp.getTongct());
         dtmkhach.addRow(vec);
         }
    }
      private void xuLyLiveSearching()
    {
        ArrayList<ReaderDTO> dsSach = bus.timlKiemSachLive(txttim.getText());
        loaddataKH(dsSach);
    }
    public void searchLive()
    {
        txttim.getDocument().addDocumentListener(new DocumentListener()
        {
              @Override
            public void insertUpdate(DocumentEvent e) {
               xuLyLiveSearching();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }   
                
                
                
        } );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JTable tblKH;
    public javax.swing.JTextField txtMIn;
    public javax.swing.JTextField txtMax;
    public javax.swing.JTextArea txtdiachi;
    public javax.swing.JTextField txtgt;
    public javax.swing.JTextField txtho;
    public javax.swing.JTextField txtidkh;
    public javax.swing.JTextField txtsdt;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
