/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Others.ImagePanel;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ADMIN
 */
public class JPnDefault extends javax.swing.JPanel {

    /**
     * Creates new form JPnDefault
     */
    public JPnDefault() {
        setSize(1000,649);
        initComponents();
           panel =new ImagePanel(
        new ImageIcon("image\\background.png").getImage());
       ImageIcon bg = new ImageIcon("image\\background.png");
       Image img = bg.getImage();
       Image temp_img = img.getScaledInstance(1000, 649, Image.SCALE_SMOOTH);
       bg = new ImageIcon(temp_img);
       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(105, 107, 109));
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setName("pn1"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 649));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\nvc.jpg")); // NOI18N
        panel.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));
    }// </editor-fold>//GEN-END:initComponents
class ImagePanel extends JPanel {

  private Image img;

  public ImagePanel(String img) {
    this(new ImageIcon(img).getImage());
  }

  public ImagePanel(Image img) {
    this.img = img;
    Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
    setPreferredSize(size);
    setMinimumSize(size);
    setMaximumSize(size);
    setSize(size);
    setLayout(null);
  }

  public void paintComponent(Graphics g) {
    g.drawImage(img, 0, 0, null);
  }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbl;
    public javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}