/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Others.*;
import DAO.EmployeeDAO;
import BUS.EmployeeBUS;
import BUS.EmployeeBUS;
import BUS.PhanQuyenBUS;
import BUS.TaiKhoanBUS;
import DTO.EmployeeDTO;
import DTO.PhanQuyenDTO;
import DTO.ReaderDTO;
import DTO.TaiKhoan;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author ADMIN
 */
public class JPnEmployee extends javax.swing.JPanel {
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    TaiKhoanBUS tkbus = new TaiKhoanBUS();
ArrayList<EmployeeDTO> dsnv = new ArrayList();   
DefaultTableModel dtmNhanvien = new DefaultTableModel();
EmployeeBUS bus = new EmployeeBUS();
ButtonGroup gender = new ButtonGroup();

    /**
     * Creates new form JPnEmployee
     */
    public JPnEmployee() {
       // dtmtk = (DefaultTableModel)tbltk.getModel();
        initComponents();
                dtmNhanvien = (DefaultTableModel)tblNhanvien.getModel();

        loadtblNhanvien();
        loadquyen();
        loadnv();
        searchLive();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JfAcc = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtuser1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cmbnv1 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txttim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label11 = new java.awt.Label();
        jLabel10 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtdc = new javax.swing.JTextArea();
        cmbquyen = new javax.swing.JComboBox();
        txtgt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        JfAcc.setMinimumSize(new java.awt.Dimension(770, 260));

        jPanel2.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Quản lý tài khoản");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 70));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nhân viên");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, 30));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tài khoản");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));
        jPanel2.add(txtuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 300, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Reset.png")); // NOI18N
        jButton5.setText("Đặt lại mật khẩu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        jButton9.setText("Thêm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 30));

        cmbnv1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(cmbnv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 300, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Lock.png")); // NOI18N
        jButton6.setText("Khóa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Lock.png")); // NOI18N
        jButton7.setText("Mở khóa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 120, 30));

        javax.swing.GroupLayout JfAccLayout = new javax.swing.GroupLayout(JfAcc.getContentPane());
        JfAcc.getContentPane().setLayout(JfAccLayout);
        JfAccLayout.setHorizontalGroup(
            JfAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(JfAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JfAccLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        JfAccLayout.setVerticalGroup(
            JfAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
            .addGroup(JfAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JfAccLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setBackground(new java.awt.Color(130, 195, 65));
        setPreferredSize(new java.awt.Dimension(1000, 649));

        jPanel3.setBackground(new java.awt.Color(130, 195, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(217, 237, 202));

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên", "Giới tính", "Chức vụ", "Địa chỉ", "SĐT"
            }
        ));
        tblNhanvien.setToolTipText("");
        tblNhanvien.setPreferredSize(new java.awt.Dimension(1000, 304));
        tblNhanvien.setShowVerticalLines(true);
        tblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanvienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanvien);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1000, 350));

        jPanel4.setBackground(new java.awt.Color(130, 195, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });
        txttim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimKeyPressed(evt);
            }
        });
        jPanel4.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tim:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 30));

        btnRemove.setBackground(new java.awt.Color(213, 214, 217));
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Delete.png")); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 120, 30));

        btnEdit.setBackground(new java.awt.Color(213, 214, 217));
        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Edit.png")); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setMaximumSize(new java.awt.Dimension(60, 28));
        btnEdit.setMinimumSize(new java.awt.Dimension(60, 28));
        btnEdit.setPreferredSize(new java.awt.Dimension(60, 28));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 120, 30));

        btnAdd.setBackground(new java.awt.Color(213, 214, 217));
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 120, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1000, 70));

        BtnUpdate.setBackground(new java.awt.Color(217, 237, 202));
        BtnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Refresh.png")); // NOI18N
        BtnUpdate.setToolTipText("");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý nhân viên");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 70));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên nhân viên");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 30));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Họ nhân viên");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, 30));

        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Giới tính");
        jPanel3.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Chức vụ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 70, 30));

        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });
        jPanel3.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 240, -1));
        jPanel3.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 260, -1));
        jPanel3.add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 240, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Mã nhân viên");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Địa chỉ");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 90, 30));

        txtma.setEditable(false);
        txtma.setBackground(new java.awt.Color(130, 195, 65));
        jPanel3.add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 240, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Số điện thoại");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 90, 30));

        txtdc.setColumns(20);
        txtdc.setRows(5);
        jPanel3.add(txtdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 260, 70));

        jPanel3.add(cmbquyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 260, -1));
        jPanel3.add(txtgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 240, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Services.png")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMouseClicked
        // TODO add your handling code here:
        // DefaultTableModel md = (DefaultTableModel)tblNhanvien.getModel();
   int i = tblNhanvien.getSelectedRow();
     try{
     txtma.setText(tblNhanvien.getValueAt(i,0).toString());
     txtho.setText(tblNhanvien.getValueAt(i,1).toString());
     txtten.setText(tblNhanvien.getValueAt(i,2).toString());
     txtdc.setText(tblNhanvien.getValueAt(i, 5).toString());
     txtgt.setText(tblNhanvien.getValueAt(i,4).toString());
     String quyen = tblNhanvien.getValueAt(i, 4).toString();
     cmbquyen.setSelectedItem(quyen);
     txtsdt.setText(tblNhanvien.getValueAt(i,6).toString());
     }catch(Exception e){System.out.println(e.toString());}
    }//GEN-LAST:event_tblNhanvienMouseClicked

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        EmployeeBUS bus = new EmployeeBUS();
        
        int i = tblNhanvien.getSelectedRow();
            if(i<0){
             JOptionPane.showMessageDialog(null,"Vui lòng chọn nhân viên muốn xóa thông tin");
             return;
         }
        if(i>=0){
            int ma = Integer.parseInt(tblNhanvien.getModel().getValueAt(i,0).toString());
            dsnv.remove(bus.timkiemtheoMa(ma));
            bus.xoa(ma);
            dtmNhanvien.removeRow(i);
            tblNhanvien.setModel(dtmNhanvien);
            JOptionPane.showMessageDialog(null,"Delete Successfully.");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
                    int i = tblNhanvien.getSelectedRow();
         if(i<0){
             JOptionPane.showMessageDialog(null,"Vui lòng chọn nhân viên muốn sửa thông tin");
             return;
         }

         if(txtten.getText().length()<=0 || txtho.getText().length()<=0 || txtgt.getText().length()<= 0 || txtdc.getText().length()<= 0 || txtsdt.getText().length()<= 0){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin");
            return;
        }
        if(i>=0){
            EmployeeDTO rd = new EmployeeDTO();
     //   rd.id = txtidkh.getText();
        rd.ho = txtho.getText();
        rd.ten = txtten.getText();
        
       // rd.ngaysinh = dateFormat.format(dob1.getDate());
        rd.gioitinh = txtgt.getText();
        rd.diachi = txtdc.getText();
        rd.sdt = Integer.parseInt(txtsdt.getText());
        
            dtmNhanvien.setValueAt(rd.id,i,0);
            dtmNhanvien.setValueAt(rd.ho,i,1);
            dtmNhanvien.setValueAt(rd.ten,i,2);
           // dtmNhanvien.setValueAt(rd.ngaysinh,i,3);
            dtmNhanvien.setValueAt(rd.gioitinh, i, 3);
            dtmNhanvien.setValueAt(rd.diachi,i,4);
            dtmNhanvien.setValueAt(rd.sdt,i,5);
            tblNhanvien.setModel(dtmNhanvien);
        bus.sua(rd);
            JOptionPane.showMessageDialog(null,"Edit Successfully.");
        
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(txtten.getText().length()<=0 || txtho.getText().length()<=0 || txtgt.getText().length()<= 0 || txtdc.getText().length()<= 0 || txtsdt.getText().length()<= 0){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin");
            return;
        }
      EmployeeDTO e = new EmployeeDTO();
      e.setho(txtho.getText());
      e.setten(txtten.getText());
      e.setgioitinh(txtgt.getText());
      e.setPhanquyen(cmbquyen.getSelectedItem().toString());
      e.setDiachi(txtdc.getText());
      e.setsdt(Integer.parseInt(txtsdt.getText()));
      e.setTt(1);
      bus.khoitao(e, dtmNhanvien, tblNhanvien);
      loadtblNhanvien();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txttimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKeyPressed
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_txttimKeyPressed

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        TaiKhoan tk = new TaiKhoan();
        EmployeeDTO e = bus.getMafromTen(cmbnv1.getSelectedItem().toString());
        tk.setManv(e.getid());
        tk.setTaikhoan( txtuser1.getText());
    //    tk.setMatkhau(txtpass1.getText());
        tk.setQuyen(e.getPhanquyen());
        tkbus.themTaiKhoan(String.valueOf(tk.getManv()), tk.getTaikhoan(),tk.getQuyen());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JfAcc.setVisible(true);
        JfAcc.setSize(750,300);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
                EmployeeDTO e = bus.getMafromTen(cmbnv1.getSelectedItem().toString());
                tkbus.datLaiMatKhau(String.valueOf(e.getid()), txtuser1.getText());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tkbus.khoaTaiKhoan(txtuser1.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        tkbus.moKhoaTaiKhoan(txtuser1.getText());
    }//GEN-LAST:event_jButton7ActionPerformed
    public void loadquyen(){
         cmbquyen.removeAll();
        PhanQuyenBUS tgbus = new PhanQuyenBUS();
        ArrayList<PhanQuyenDTO> tacgiaList = tgbus.getListQuyen();

       // cmbtacgia.addItem(" ");

        for (PhanQuyenDTO DataBox : tacgiaList) {
            cmbquyen.addItem(DataBox.getQuyen());
        }
     //   cmbtheloai.addItem("Het");
    

    }
    public void loadnv(){
         cmbnv1.removeAll();
        
        ArrayList<EmployeeDTO> tacgiaList = bus.getdsnv();

       // cmbtacgia.addItem(" ");

        for (EmployeeDTO DataBox : tacgiaList) {
            cmbnv1.addItem(DataBox.getho() + " " + DataBox.getten());
        }
     //   cmbtheloai.addItem("Het");
    

    }
    DefaultTableModel dtmtk = new DefaultTableModel();
    ArrayList<TaiKhoan> dstk = new ArrayList();
   
    
    public void loadtblNhanvien(){
    dtmNhanvien.setRowCount(0);
       dsnv = EmployeeBUS.getdsnv();
     Vector header = new Vector();
        header.add("Mã nhân viên");
        header.add("Họ");
        header.add("Tên");
        header.add("Giới tính");
        header.add("Chức vụ");
        header.add("Địa chỉ");
        //header.add("Ngày sinh");
        header.add("Số điện thoại");
        if(dtmNhanvien.getRowCount()==0){
            dtmNhanvien = new DefaultTableModel(header,0);
            
        }
        for (EmployeeDTO nv : dsnv) {
            Vector vec = new Vector();
            vec.add(nv.getid());
            vec.add(nv.getho());
            vec.add(nv.getten());
            vec.add(nv.getgioitinh());
            vec.add(nv.getPhanquyen());
            vec.add(nv.getDiachi());
        //    vec.add(nv.getngaysinh());
            
            vec.add(nv.getsdt());
            
            dtmNhanvien.addRow(vec);
        }
        tblNhanvien.setModel(dtmNhanvien);
           
        }
 private void loaddatanv(ArrayList<EmployeeDTO> dskh) {
        dtmNhanvien.setRowCount(0);
        DecimalFormat dcf = new DecimalFormat("###,###");
        for (EmployeeDTO kh : dskh) {
            Vector vec = new Vector();
            vec.add(kh.getid());
            vec.add(kh.getho());
            vec.add(kh.getten());
            vec.add(kh.getgioitinh());
            vec.add(kh.getPhanquyen());
            vec.add(kh.getDiachi());
            vec.add(kh.getsdt());
            dtmNhanvien.addRow(vec);
        }
    }
private void xuLyXuatExcel() {
        XuLyFileExcel xuatExcel = new XuLyFileExcel();
        xuatExcel.xuatExcel(tblNhanvien);
}
private void xulyNhapExcel(){
        XuLyFileExcel nhapExcel = new XuLyFileExcel();
        nhapExcel.nhapExcel(tblNhanvien);
}
    private void xuLyLiveSearching()
    {
        ArrayList<EmployeeDTO> dsSach = bus.timlKiemSachLive(txttim.getText());
        loaddatanv(dsSach);
    }
    public void searchLive()
    {
        txttim.getDocument().addDocumentListener(new DocumentListener()
        {
              @Override
            public void insertUpdate(DocumentEvent e) {
               xuLyLiveSearching();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }   
                
                
                
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnUpdate;
    public javax.swing.JFrame JfAcc;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnRemove;
    public javax.swing.JComboBox cmbnv1;
    public javax.swing.JComboBox cmbquyen;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane3;
    public java.awt.Label label11;
    public javax.swing.JTable tblNhanvien;
    public javax.swing.JTextArea txtdc;
    public javax.swing.JTextField txtgt;
    public javax.swing.JTextField txtho;
    public javax.swing.JTextField txtma;
    public javax.swing.JTextField txtsdt;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txttim;
    public javax.swing.JTextField txtuser1;
    // End of variables declaration//GEN-END:variables
}
