/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DTO.*;
import BUS.*;
import DAO.sachDAO;
import DTO.theLoaiDTO;
import Others.MyFileChooser;
import Others.MyTableCellRenderer;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class JPnImport extends javax.swing.JPanel {
 theLoaiiBUS theloai_bus = new theLoaiiBUS();
    sachBUS sach_bus = new sachBUS();
    tacgiaBUS tgbus = new tacgiaBUS();
    PhieuNhapBUS pnbus = new PhieuNhapBUS();
    CTPhieuNhapBUS ctpnbus = new CTPhieuNhapBUS();
    DefaultTableModel dtmpn = new DefaultTableModel();
    DefaultTableModel dtmctpn = new DefaultTableModel();
    
DefaultTableModel dtmkho = new DefaultTableModel();
ArrayList<sachDTO> listSach = new ArrayList<>();

  //  theLoaiiBUS theloai_bus = new theLoaiiBUS();
    /**
     * Creates new form JPnImport
     */
    public JPnImport() {
        initComponents();
         dtmkho = (DefaultTableModel) tblKho.getModel();
         dtmcart = (DefaultTableModel) tblNhap.getModel();
         dtmpn = (DefaultTableModel) tblpn.getModel();
         dtmctpn = (DefaultTableModel) tblctpn.getModel();
                 dtmsearch = (DefaultTableModel) tblKho.getModel();

         loadDataLenBangSanPham();
         loadDataCmbMaTheLoai(); //load data combo box the loai khi them dau sach
         loadDataCmbMatacgia(); //load data combo box tac gia khi them dau sach
         loadDataCmbNV(); //load data combo box nhan vien khi lap phieu nhap
         loadDatapn(); //load data cac phieu nhap
         loadDatactpn();    // load data cac chi tiet phieu nhap
         searchLive(); //ho tro tim kiem nhanh san pham

                 dtmcart.setRowCount(0);
                                tblKho.setDefaultRenderer(Object.class, new MyTableCellRenderer(4));//combo box filter bang san pham


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfAdd = new javax.swing.JFrame();
        pnAdd1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtnam = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        lbanh = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmbtheloai = new javax.swing.JComboBox();
        btnChoose = new java.awt.Button();
        cmbtacgia = new javax.swing.JComboBox();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKho = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhap = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtgianhap = new javax.swing.JTextField();
        txtsl = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txttenhang = new javax.swing.JTextField();
        txtmahang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbnv = new javax.swing.JComboBox();
        btnDeleteCart = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        cmbSort = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txttimngay2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txttimgia1 = new javax.swing.JTextField();
        txttimgia2 = new javax.swing.JTextField();
        txttimngay1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpn = new javax.swing.JTable();
        txttongtien = new javax.swing.JTextField();
        txtmapn = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        txtngay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmapn2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsl2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdongia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtthanhtien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblctpn = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jfAdd.setMinimumSize(new java.awt.Dimension(1000, 330));

        pnAdd1.setBackground(new java.awt.Color(130, 195, 65));
        pnAdd1.setMaximumSize(new java.awt.Dimension(1000, 300));
        pnAdd1.setMinimumSize(new java.awt.Dimension(1000, 300));
        pnAdd1.setPreferredSize(new java.awt.Dimension(700, 300));
        pnAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Thêm đầu sách");
        pnAdd1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 5, 1020, -1));

        btnAdd1.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add.png")); // NOI18N
        btnAdd1.setText("Thêm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        pnAdd1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 190, -1));

        jLabel26.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Mã sách");
        pnAdd1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel27.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tên sách");
        pnAdd1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 80, -1));

        jLabel28.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tác giả");
        pnAdd1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Năm sản xuất");
        pnAdd1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel30.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Giá nhập");
        pnAdd1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        txtma.setEditable(false);
        txtma.setBackground(new java.awt.Color(204, 204, 204));
        txtma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaKeyPressed(evt);
            }
        });
        pnAdd1.add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, -1));
        pnAdd1.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 230, -1));
        pnAdd1.add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 230, -1));
        pnAdd1.add(txtgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, -1));

        lbanh.setForeground(new java.awt.Color(255, 255, 255));
        lbanh.setToolTipText("");
        lbanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbanh.setMinimumSize(new java.awt.Dimension(200, 200));
        lbanh.setPreferredSize(new java.awt.Dimension(200, 200));
        pnAdd1.add(lbanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 200, 200));

        jLabel32.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Thể loại");
        pnAdd1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cmbtheloai.setBackground(new java.awt.Color(255, 255, 255));
        pnAdd1.add(cmbtheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, -1));

        btnChoose.setLabel("Chọn ảnh");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        pnAdd1.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, 30));

        cmbtacgia.setBackground(new java.awt.Color(255, 255, 255));
        pnAdd1.add(cmbtacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, -1));

        jfAdd.getContentPane().add(pnAdd1, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(130, 195, 65));
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setPreferredSize(new java.awt.Dimension(1000, 649));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(130, 195, 65));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(130, 195, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 649));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 649));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 20));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Thông tin phiếu nhập");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 300, -1));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 550));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 300, 10));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Hàng chờ nhập");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 350, 700, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 300, 20));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Thông tin sản phẩm");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        tblKho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tồn kho", "Giá nhập", "Trạng thái"
            }
        ));
        tblKho.setShowVerticalLines(true);
        tblKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKho);
        if (tblKho.getColumnModel().getColumnCount() > 0) {
            tblKho.getColumnModel().getColumn(0).setMinWidth(30);
            tblKho.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblKho.getColumnModel().getColumn(0).setMaxWidth(100);
            tblKho.getColumnModel().getColumn(2).setMinWidth(30);
            tblKho.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblKho.getColumnModel().getColumn(2).setMaxWidth(100);
            tblKho.getColumnModel().getColumn(3).setMinWidth(30);
            tblKho.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblKho.getColumnModel().getColumn(3).setMaxWidth(100);
            tblKho.getColumnModel().getColumn(4).setMinWidth(30);
            tblKho.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblKho.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, 270));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Đơn giá nhập");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 300, 30));

        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });
        jPanel1.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 320, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Kho hàng");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        tblNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá nhập", "Thành tiền"
            }
        ));
        tblNhap.setShowVerticalLines(true);
        jScrollPane4.setViewportView(tblNhap);
        if (tblNhap.getColumnModel().getColumnCount() > 0) {
            tblNhap.getColumnModel().getColumn(0).setMinWidth(30);
            tblNhap.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblNhap.getColumnModel().getColumn(0).setMaxWidth(100);
            tblNhap.getColumnModel().getColumn(2).setMinWidth(30);
            tblNhap.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblNhap.getColumnModel().getColumn(2).setMaxWidth(100);
            tblNhap.getColumnModel().getColumn(3).setMinWidth(30);
            tblNhap.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblNhap.getColumnModel().getColumn(3).setMaxWidth(100);
            tblNhap.getColumnModel().getColumn(4).setMinWidth(30);
            tblNhap.getColumnModel().getColumn(4).setPreferredWidth(70);
            tblNhap.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 680, 160));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tìm");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 30, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mã sách");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 60, 30));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nhân viên");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 90, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Số lượng nhập");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 300, 30));

        txtgianhap.setEditable(false);
        txtgianhap.setBackground(new java.awt.Color(130, 195, 65));
        jPanel1.add(txtgianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 280, -1));
        jPanel1.add(txtsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 280, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Shopping Cart.png")); // NOI18N
        jButton2.setText("Chọn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 110, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tên sách");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 60, 30));

        txttenhang.setEditable(false);
        txttenhang.setBackground(new java.awt.Color(130, 195, 65));
        jPanel1.add(txttenhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 200, -1));

        txtmahang.setEditable(false);
        txtmahang.setBackground(new java.awt.Color(130, 195, 65));
        jPanel1.add(txtmahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add Book.png")); // NOI18N
        jButton1.setText("Thêm đầu sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, 30));

        cmbnv.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmbnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 190, 30));

        btnDeleteCart.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Remove Book.png")); // NOI18N
        btnDeleteCart.setText("Xóa");
        btnDeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 110, -1));

        btnbill.setBackground(new java.awt.Color(255, 255, 255));
        btnbill.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Bill.png")); // NOI18N
        btnbill.setText("Xác nhận");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        jPanel1.add(btnbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 110, -1));

        cmbSort.setBackground(new java.awt.Color(255, 255, 255));
        cmbSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã", "Tên", "Giá giảm dần", "Giá tăng dần", "Tồn kho giảm dần", "Tồn kho tăng dần" }));
        cmbSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSortItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        jTabbedPane2.addTab("Nhập hàng", jPanel1);

        jPanel2.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết phiếu nhập");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 670, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 10, 620));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phiếu nhập");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 330, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tổng tiền");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã PN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã NV");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày lập");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ngày lập từ");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("đến");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 30));

        txttimngay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimngay2ActionPerformed(evt);
            }
        });
        jPanel2.add(txttimngay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, 30));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Giá từ");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 50));

        txttimgia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimgia1ActionPerformed(evt);
            }
        });
        jPanel2.add(txttimgia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 30));

        txttimgia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimgia2ActionPerformed(evt);
            }
        });
        jPanel2.add(txttimgia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, 30));

        txttimngay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimngay1ActionPerformed(evt);
            }
        });
        jPanel2.add(txttimngay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 80, 30));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("đến");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 30));

        tblpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã PN", "Ngày lập", "Tổng tiền"
            }
        ));
        tblpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpn);
        if (tblpn.getColumnModel().getColumnCount() > 0) {
            tblpn.getColumnModel().getColumn(0).setMinWidth(30);
            tblpn.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblpn.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, 310));

        txttongtien.setEditable(false);
        txttongtien.setBackground(new java.awt.Color(130, 195, 65));
        txttongtien.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txttongtien.setForeground(new java.awt.Color(255, 255, 255));
        txttongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttongtienActionPerformed(evt);
            }
        });
        jPanel2.add(txttongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, -1));

        txtmapn.setEditable(false);
        txtmapn.setBackground(new java.awt.Color(130, 195, 65));
        txtmapn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtmapn.setForeground(new java.awt.Color(255, 255, 255));
        txtmapn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmapnActionPerformed(evt);
            }
        });
        jPanel2.add(txtmapn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, -1));

        txtmanv.setEditable(false);
        txtmanv.setBackground(new java.awt.Color(130, 195, 65));
        txtmanv.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtmanv.setForeground(new java.awt.Color(255, 255, 255));
        txtmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanvActionPerformed(evt);
            }
        });
        jPanel2.add(txtmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));

        txtngay.setEditable(false);
        txtngay.setBackground(new java.awt.Color(130, 195, 65));
        txtngay.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtngay.setForeground(new java.awt.Color(255, 255, 255));
        txtngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayActionPerformed(evt);
            }
        });
        jPanel2.add(txtngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã PN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtmapn2.setEditable(false);
        txtmapn2.setBackground(new java.awt.Color(130, 195, 65));
        txtmapn2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtmapn2.setForeground(new java.awt.Color(255, 255, 255));
        txtmapn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmapn2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtmapn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 340, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sản phẩm");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        txtsp.setEditable(false);
        txtsp.setBackground(new java.awt.Color(130, 195, 65));
        txtsp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtsp.setForeground(new java.awt.Color(255, 255, 255));
        txtsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspActionPerformed(evt);
            }
        });
        jPanel2.add(txtsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 340, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Số lượng");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        txtsl2.setEditable(false);
        txtsl2.setBackground(new java.awt.Color(130, 195, 65));
        txtsl2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtsl2.setForeground(new java.awt.Color(255, 255, 255));
        txtsl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsl2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtsl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 340, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Đơn giá");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        txtdongia.setEditable(false);
        txtdongia.setBackground(new java.awt.Color(130, 195, 65));
        txtdongia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtdongia.setForeground(new java.awt.Color(255, 255, 255));
        txtdongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdongiaActionPerformed(evt);
            }
        });
        jPanel2.add(txtdongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 340, -1));

        jLabel25.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Thành tiền");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        txtthanhtien.setEditable(false);
        txtthanhtien.setBackground(new java.awt.Color(130, 195, 65));
        txtthanhtien.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtthanhtien.setForeground(new java.awt.Color(255, 255, 255));
        txtthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthanhtienActionPerformed(evt);
            }
        });
        jPanel2.add(txtthanhtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 340, -1));

        tblctpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblctpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblctpnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblctpn);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 630, 350));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Refresh.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 8, 60, 40));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Search.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 40, 30));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Search.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 40, 30));

        jTabbedPane2.addTab("Xem phiếu nhập", jPanel2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txttimngay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimngay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimngay2ActionPerformed

    private void txttimgia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimgia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimgia1ActionPerformed

    private void txttimgia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimgia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimgia2ActionPerformed

    private void txttimngay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimngay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimngay1ActionPerformed

    private void txttongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttongtienActionPerformed

    private void txtmapnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmapnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmapnActionPerformed

    private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanvActionPerformed

    private void txtngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngayActionPerformed

    private void txtmapn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmapn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmapn2ActionPerformed

    private void txtspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspActionPerformed

    private void txtsl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsl2ActionPerformed

    private void txtdongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdongiaActionPerformed

    private void txtthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthanhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthanhtienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jfAdd.setVisible(true);
        jfAdd.setSize(1000,400);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtma.setEditable(true);
            txtma.setBackground(new Color(255,255,255));

        }
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            txtma.setEditable(false);
            txtma.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtmaKeyPressed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        xuLyChonAnh();
    }//GEN-LAST:event_btnChooseActionPerformed
       File fileAnhSach;
       public void xuLyChonAnh() {
        JFileChooser fileChooser = new MyFileChooser("image/book/");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp hình ảnh", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileAnhSach = fileChooser.getSelectedFile();
            lbanh.setIcon(getAnhSach(fileAnhSach.getPath()));
        }

    }
    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        sachDAO dao = new sachDAO();
        sachBUS bus = new sachBUS();
        sachDTO rd = new sachDTO();
        if(txtten.getText().trim().equals("") || txtnam.getText().trim().equals("") || cmbtheloai.getSelectedItem().toString().trim().equals("Chọn thể loại") ||txtten.getText().trim().equals("") || cmbtacgia.getSelectedItem().toString().trim().equals("Chọn tác giả") ){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin");
            return;
        }
//        rd.Ma =Integer.parseInt( txtma.getText());
        rd.Ten=txtten.getText();
        rd.MaTacGia= tgbus.getMafromTen(cmbtacgia.getSelectedItem().toString());
        rd.MaTheLoai= theloai_bus.getMafromTen(cmbtheloai.getSelectedItem().toString()) ;
        rd.NamSanXuat = Integer.parseInt(txtnam.getText());
        String anh = fileAnhSach.getName();
        rd.Anh = anh;
        rd.soLuong = 0;
        rd.Gia = Double.parseDouble(txtgia.getText());
        rd.tt = 1;
        
   //     boolean flag = sach_bus.themSach(txtten.getText(), cmbtacgia.getSelectedItem() + "", cmbtheloai.getSelectedItem() + "", txtnam.getText(), anh, txtgia.getText());

        Vector header = new Vector();
        header.add("Mã sách");
        header.add("Tên sách");
        header.add("Mã tác giả");
        header.add("Mã thể loại");
        header.add("Năm sản xuất");
        header.add("Số lượng");
        header.add("Giá");
        header.add("Trạng thái");
   if(dtmkho.getRowCount()==0){
       dtmkho = new DefaultTableModel(header,0);
   }
   bus.khoitao(rd,dtmkho,tblKho);
   
   loadDataLenBangSanPham();
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void tblKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoMouseClicked
        // TODO add your handling code here:
         DefaultTableModel md = (DefaultTableModel)tblKho.getModel();
         int viewRow = tblKho.getSelectedRow (); // Get the selected row in the view
int modelRow = tblKho.convertRowIndexToModel (viewRow); // Convert it to the model row
//Object value = tblKho.getModel ().getValueAt (modelRow, 0); // Get the value of the model row
  //      int i = tblKho.getSelectedRow();
         try{
     txtmahang.setText(tblKho.getModel().getValueAt(modelRow, 0).toString());
     txttenhang.setText(tblKho.getModel().getValueAt(modelRow, 1).toString());
     txtgianhap.setText(tblKho.getModel().getValueAt(modelRow, 3).toString());
   
     }catch(Exception e){System.out.println(e.toString());}
    }//GEN-LAST:event_tblKhoMouseClicked
DefaultTableModel dtmcart = new DefaultTableModel();
ArrayList<sachDTO> cartlist = new ArrayList<sachDTO>();
ArrayList<CTPhieuNhap> ctphieunhap = new ArrayList();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        sachDTO s = new sachDTO();
        CTPhieuNhap ct = new CTPhieuNhap();
        
         int row = tblKho.getSelectedRow();
         if(row<0){
             JOptionPane.showMessageDialog(null,"Vui lòng chọn đầu sách");
             return;
         }else if(txtsl.getText().trim().equals("0")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng lớn hơn 0");
            return;
         }else if(txtsl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng");
            return;
         }
         if(tblKho.getValueAt(row, 4).equals("Còn xuất bản")){
        if (row > -1) {
            ct.maPN = 0;
            ct.maSP = Integer.parseInt(tblKho.getValueAt(row, 0) + "");
            ct.soLuong = Integer.parseInt(txtsl.getText());
            ct.donGia = Double.parseDouble(tblKho.getValueAt(row, 3) + "");
            ct.thanhTien = ct.soLuong * ct.donGia;
            
        }
        ctphieunhap.add(ct);
         Vector vec = new Vector();
          //  vec.add(ct.getMaPN());
            vec.add(ct.getMaSP());
            vec.add(sach_bus.getTenSP(ct.getMaSP()));
            vec.add(ct.getSoLuong());
            vec.add(ct.getDonGia());
            vec.add(ct.getThanhTien());
           
        dtmcart.addRow(vec);
        tblNhap.setModel(dtmcart);}
         else {JOptionPane.showMessageDialog(null,"Sách đã ngưng xuất bản, không thể nhập thêm!");
                return;}
         
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
         if(cmbnv.getSelectedItem().toString().equalsIgnoreCase("0 - chọn nhân viên")){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn nhân viên phụ trách hóa đơn");
            return;
        }
        if(ctphieunhap.size() <= 0){
            JOptionPane.showMessageDialog(null,"Lô hàng trống, không thể tạo phiếu nhập");
            return;
        }else{
            int tong = 0;
            for(CTPhieuNhap s : ctphieunhap){
                tong += s.thanhTien;
            }
            EmployeeBUS ebus = new EmployeeBUS();
            EmployeeDTO e = new EmployeeDTO();
            e = ebus.getMafromTen(cmbnv.getSelectedItem().toString());
            String name = e.ho + " " + e.ten;
            if(!cmbnv.getSelectedItem().equals("Chọn nhân viên")){
            XuatPhieuNhapGUI xuatpn = new XuatPhieuNhapGUI(name,ctphieunhap,tong);
            xuatpn.setVisible(true);
            xuatpn.setSize(532,440);
            loadDataLenBangSanPham();}
            else return;
        }
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCartActionPerformed
        // TODO add your handling code here:
         int row = tblNhap.getSelectedRow();
        ctphieunhap.remove(row);
        dtmcart.removeRow(row);
        tblNhap.setModel(dtmcart);
    }//GEN-LAST:event_btnDeleteCartActionPerformed

    private void cmbSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSortItemStateChanged
        // TODO add your handling code here:
        if(cmbSort.getSelectedItem() == "Mã"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Mã sách").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }else if(cmbSort.getSelectedItem() == "Tên"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Tên sách").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        if(cmbSort.getSelectedItem() == "Giá tăng dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Giá nhập").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }else if(cmbSort.getSelectedItem() == "Giá giảm dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Giá nhập").getModelIndex(), SortOrder.DESCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if(cmbSort.getSelectedItem() == "Tồn kho tăng dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Tồn kho").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }else if(cmbSort.getSelectedItem() == "Tồn kho giảm dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblKho.getModel());
            tblKho.setRowSorter(sorter);
            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblKho.getColumn("Tồn kho").getModelIndex(), SortOrder.DESCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_cmbSortItemStateChanged

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
           xuLyLiveSearching();
    }//GEN-LAST:event_txttimActionPerformed

    private void tblpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpnMouseClicked
        // TODO add your handling code here:
         int row = tblpn.getSelectedRow();
        if (row < 0) {
            return;
        }
        String maPN = tblpn.getValueAt(row, 0) + "";
        PhieuNhap pn = pnbus.timPhieuNhap(maPN);
        txtmapn.setText(pn.getMaPN() + "");
       // txtMaN.setText(pn.getMaNCC() + "");
        txtmanv.setText(pn.getMaNV() + "");
        txtngay.setText(pn.getNgayLap().toString());
        txttongtien.setText(String.valueOf(pn.getTongTien()));

        loadDataTableCTPhieuNhap(maPN);
    }//GEN-LAST:event_tblpnMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        loadDatapn();
        loadDatactpn();
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void tblctpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblctpnMouseClicked
        // TODO add your handling code here:
        int row = tblctpn.getSelectedRow();
        int r = tblpn.getSelectedRow();
        if (row < 0) {
            return;
        }
        txtmapn2.setText(tblpn.getValueAt(r,0).toString());
        String tenSP = sach_bus.getTenSP(Integer.parseInt(tblctpn.getValueAt(row, 0) + ""));
        txtsp.setText(tenSP);
        txtsl2.setText(tblctpn.getValueAt(row, 1) + "");
        txtdongia.setText(tblctpn.getValueAt(row, 2) + "");
        txtthanhtien.setText(tblctpn.getValueAt(row, 3) + "");
    }//GEN-LAST:event_tblctpnMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadDatapn();
        loadDatactpn();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dtmpn.setRowCount(0);

        ArrayList<PhieuNhap> dssp = pnbus.getListPhieuNhapTheoNgay(txttimngay1.getText(), txttimngay2.getText());

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (PhieuNhap sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaPN());
            //vec.add(sp.getMaNV());
            //vec.add(sp.getMaKH());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            //vec.add(sp.getGhiChu());

            dtmpn.addRow(vec);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        dtmpn.setRowCount(0);

        ArrayList<PhieuNhap> dssp = pnbus.getListPhieuNhapTheoGia(txttimgia1.getText(), txttimgia2.getText());

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (PhieuNhap sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaPN());
            //vec.add(sp.getMaNV());
            //vec.add(sp.getMaKH());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            //vec.add(sp.getGhiChu());

            dtmpn.addRow(vec);

        }

    }//GEN-LAST:event_jButton5ActionPerformed
    private void xuLyLiveSearching()
    {
        ArrayList<sachDTO> dsSach = sach_bus.timlKiemSachLive(txttim.getText());
        loadDataLenBangSanPham(dsSach);
    }
    public void searchLive()
    {
        txttim.getDocument().addDocumentListener(new DocumentListener()
        {
              @Override
            public void insertUpdate(DocumentEvent e) {
               xuLyLiveSearching();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }   
                
                
                
        } );
    }
    
    
    private void luuAnhFile() {
        BufferedImage bImage = null;
        try {
            File initialImage = new File(fileAnhSach.getPath());
            bImage = ImageIO.read(initialImage);
            ImageIO.write(bImage, "png", new File("image/book/" + fileAnhSach.getName()));
        } catch (IOException e) {

        }

    }
    public void loadDataCmbMaTheLoai() {
        cmbtheloai.removeAll();
        ArrayList<theLoaiDTO> theloaiList = theloai_bus.getDanhSachLoai();

        cmbtheloai.addItem("Chọn thể lọai");

        for (theLoaiDTO DataBox : theloaiList) {
            cmbtheloai.addItem( DataBox.getTen());
        }
        cmbtheloai.addItem("Het");
    }
 public void loadDataCmbMatacgia (){
        cmbtacgia.removeAll();
        tacgiaBUS tgbus = new tacgiaBUS();
        ArrayList<tacGiaDTO> tacgiaList = tgbus.getDanhSachTacGia();

        cmbtacgia.addItem("Chọn tác giả");

        for (tacGiaDTO DataBox : tacgiaList) {
            cmbtacgia.addItem(DataBox.getTen());
        }
        cmbtheloai.addItem("Het");
    }
    DefaultTableModel dtmsearch = new DefaultTableModel();
 private void loadDataLenBangSanPham( ArrayList<sachDTO> dssp) {
        // sach_bus.doclistSach();
        dtmsearch.setRowCount(0);

       // ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
            vec.add(sp.getMaTacGia());
            vec.add(sp.getMaTheLoai());
            vec.add(sp.getNamSanXuat());
            vec.add(sp.getSoLuong());
            vec.add(sp.getAnh());
            vec.add(sp.getGia());

            dtmsearch.addRow(vec);

        }
    }
private void loadAnh(String anh) {
        lbanh.setIcon(getAnhSach(anh));}
    private ImageIcon getAnhSach(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        BufferedImage img = null;
        File fileImg = new File(src);
        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/book" + src);
        }
        try {
            img = ImageIO.read(fileImg);
            fileAnhSach = new File(src);

        } catch (IOException e) {

        }
        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);

        }
        return null;

    }
private void loadDataLenBangSanPham() {
        sach_bus.doclistSach();
        dtmkho.setRowCount(0);

        ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
            vec.add(sp.getSoLuong());
            double gianhap = sp.getGia() * 80/100;
            vec.add(gianhap);
            int tt = sp.getTt();
            String trangthai = "";
            if (tt == 1){
                trangthai = "Còn xuất bản";
            }
            else trangthai = "Ngưng xuất bản";
            vec.add(trangthai);
            dtmkho.addRow(vec);
            
        
        }
}
 public void loadDataCmbNV(){
        cmbnv.removeAll();
        EmployeeBUS tgbus = new EmployeeBUS();
        ArrayList<EmployeeDTO> tacgiaList = tgbus.getdsnv();

        cmbnv.addItem("Chọn nhân viên");

        for (EmployeeDTO DataBox : tacgiaList) {
            cmbnv.addItem(DataBox.getho() + " " + DataBox.getten());
        }
    }
    
  private void loadDatapn() {
        dtmpn.setRowCount(0);

        ArrayList<PhieuNhap> dssp = pnbus.getListPhieuNhap();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (PhieuNhap sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaPN());
            //vec.add(sp.getMaNV());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            dtmpn.addRow(vec);
     
        }
    }
   private void loadDatactpn() {
        dtmctpn.setRowCount(0);

        ArrayList<CTPhieuNhap> dssp = ctpnbus.getListPhieuNhap();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (CTPhieuNhap sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaPN());
            vec.add(sp.getMaSP());
            vec.add(sp.getSoLuong());
            vec.add(sp.getDonGia());
            vec.add(sp.getThanhTien());
            dtmctpn.addRow(vec);
     
        }
    }
       private void loadDataTableCTPhieuNhap(String maPN) {
        dtmctpn.setRowCount(0);
        ArrayList<CTPhieuNhap> dsct = ctpnbus.getListPhieuNhap(maPN);
        if (dsct != null) {
            for (CTPhieuNhap ct : dsct) {
                Vector vec = new Vector();
                vec.add(ct.getMaSP());
                vec.add((ct.getSoLuong()));
                vec.add((ct.getDonGia()));
                vec.add((ct.getThanhTien()));
                dtmctpn.addRow(vec);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd1;
    public java.awt.Button btnChoose;
    public javax.swing.JButton btnDeleteCart;
    public javax.swing.JButton btnbill;
    public javax.swing.JComboBox cmbSort;
    public javax.swing.JComboBox cmbnv;
    public javax.swing.JComboBox cmbtacgia;
    public javax.swing.JComboBox cmbtheloai;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator10;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JSeparator jSeparator9;
    public javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JFrame jfAdd;
    public javax.swing.JLabel lbanh;
    public javax.swing.JPanel pnAdd1;
    public javax.swing.JTable tblKho;
    public javax.swing.JTable tblNhap;
    public javax.swing.JTable tblctpn;
    public javax.swing.JTable tblpn;
    public javax.swing.JTextField txtdongia;
    public javax.swing.JTextField txtgia;
    public javax.swing.JTextField txtgianhap;
    public javax.swing.JTextField txtma;
    public javax.swing.JTextField txtmahang;
    public javax.swing.JTextField txtmanv;
    public javax.swing.JTextField txtmapn;
    public javax.swing.JTextField txtmapn2;
    public javax.swing.JTextField txtnam;
    public javax.swing.JTextField txtngay;
    public javax.swing.JTextField txtsl;
    public javax.swing.JTextField txtsl2;
    public javax.swing.JTextField txtsp;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txttenhang;
    public javax.swing.JTextField txtthanhtien;
    public javax.swing.JTextField txttim;
    public javax.swing.JTextField txttimgia1;
    public javax.swing.JTextField txttimgia2;
    public javax.swing.JTextField txttimngay1;
    public javax.swing.JTextField txttimngay2;
    public javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
}
