/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.XuatHoaDonGUI;
import BUS.*;
import DTO.CTHoaDon;
import DTO.EmployeeDTO;
import DTO.HoaDon;
import DTO.sachDTO;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class JPnService extends javax.swing.JPanel {
    theLoaiiBUS theloai_bus = new theLoaiiBUS();
    sachBUS sach_bus = new sachBUS();
    HoaDonBUS hdbus = new HoaDonBUS();
    CTHoaDonBUS cthdbus = new CTHoaDonBUS();
    tacgiaBUS tgbus = new tacgiaBUS();
DefaultTableModel dtmsach = new DefaultTableModel();
DefaultTableModel dtmhd = new DefaultTableModel();
DefaultTableModel dtmcthd = new DefaultTableModel();


ArrayList<sachDTO> listSach = new ArrayList<>();
    /**
     * Creates new form JPnService
     */
    public JPnService() {
        initComponents();
        JTableHeader header = tblSach.getTableHeader();
        dtmsearch = (DefaultTableModel) tblSach.getModel();
        dtmsach = (DefaultTableModel) tblSach.getModel();
        dtmhd = (DefaultTableModel) tblhoadon.getModel();
        dtmcart =  (DefaultTableModel) tblGiohang.getModel();
        dtmcthd = (DefaultTableModel) tblcthoadon.getModel();
        tblSach.setRowHeight(25);
        loadDataLenBangSanPham();
        loadDatacthd();
        loadDataHoaDon();
        searchLive();
        dtmcart.setRowCount(0);
        loadDataCmbNV();
       // control();
    }
    private void control(){
              txtsl1.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {

            int key = e.getKeyChar();

            /* Restrict input to only integers */
            if (e.getKeyChar() >='0' && e.getKeyChar() <='9') e.setKeyChar(e.getKeyChar());
        };
    });
    }
    private void loadDataHoaDon() {//load các hóa đơn
               
                dtmhd.setRowCount(0);

        ArrayList<HoaDon> dssp = hdbus.getListHoaDon();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (HoaDon sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaHD());
            //vec.add(sp.getMaNV());
            //vec.add(sp.getMaKH());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            //vec.add(sp.getGhiChu());

            dtmhd.addRow(vec);
     
        }
    }
     
     
    private void loadDatacthd() { // load các chi tiết hóa đơn
        dtmcthd.setRowCount(0);

        ArrayList<CTHoaDon> dssp = cthdbus.getListCTHoaDon();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (CTHoaDon sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaHD());
            vec.add(sp.getMaSP());
            vec.add(sp.getSoLuong());
            vec.add(sp.getDonGia());
            vec.add(sp.getThanhTien());
            dtmcthd.addRow(vec);
     
        }
    }
private void loadDataLenBangSanPham() {//load sản phẩm lên bảng sản phẩm
        sach_bus.doclistSach();
        dtmsach.setRowCount(0);
        
        ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
            vec.add(tgbus.getTentg(sp.getMaTacGia()));
            vec.add(theloai_bus.getTenloai(sp.getMaTheLoai()));
            vec.add(sp.getNamSanXuat());
            vec.add(sp.getSoLuong());
            vec.add(sp.getAnh());
            vec.add(sp.getGia());

            dtmsach.addRow(vec);
     
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtab = new javax.swing.JTabbedPane();
        JpnSell = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmasach1 = new javax.swing.JTextField();
        txttacgia = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        lbanh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbTheloai = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCart = new javax.swing.JButton();
        txttensach1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGiohang = new javax.swing.JTable();
        txtsl1 = new javax.swing.JTextField();
        btnDeleteCart = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cmbnv = new javax.swing.JComboBox();
        cmbSort = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jPnHoadon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttrangthaihd = new javax.swing.JTextField();
        txtngaylap = new javax.swing.JTextField();
        txtmahd1 = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        txtmakh = new javax.swing.JTextField();
        txttonghd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txttimngay2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txttimgia1 = new javax.swing.JTextField();
        txttimgia2 = new javax.swing.JTextField();
        txttimngay1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtmahd2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txttensach2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtsl = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtdongia = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtthanhtien = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblcthoadon = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(130, 195, 65));
        setMaximumSize(new java.awt.Dimension(1000, 649));
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setPreferredSize(new java.awt.Dimension(1000, 649));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpnSell.setBackground(new java.awt.Color(130, 195, 65));
        JpnSell.setMinimumSize(new java.awt.Dimension(1000, 649));

        jPanel2.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.setMinimumSize(new java.awt.Dimension(1010, 649));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1010, 649));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Tác giả", "Thể loại", "Năm sản xuất", "Số lượng", "Ảnh", "Giá"
            }
        ));
        tblSach.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblSach.setShowHorizontalLines(true);
        tblSach.setShowVerticalLines(true);
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Giỏ hàng");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 140, 60));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã sách");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên sách");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 60, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tác giả");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nhân viên");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 100, 20));

        txtmasach1.setEditable(false);
        txtmasach1.setBackground(new java.awt.Color(130, 195, 65));
        txtmasach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasach1ActionPerformed(evt);
            }
        });
        txtmasach1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmasach1KeyPressed(evt);
            }
        });
        jPanel2.add(txtmasach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 200, 30));

        txttacgia.setEditable(false);
        txttacgia.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.add(txttacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 200, 30));

        txtgia.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.add(txtgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 200, 30));

        lbanh.setForeground(new java.awt.Color(255, 255, 255));
        lbanh.setToolTipText("");
        lbanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbanh.setMinimumSize(new java.awt.Dimension(200, 200));
        lbanh.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.add(lbanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 200, 200));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ảnh");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 250, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số lượng");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, 30));

        jlbTheloai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTheloaiMouseClicked(evt);
            }
        });
        jPanel2.add(jlbTheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });
        jPanel2.add(txttim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 280, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tìm kiếm");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 90, 30));

        jSeparator1.setBackground(new java.awt.Color(105, 107, 109));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(null);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 10, 650));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Chi tiết sách");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 210, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Danh sách sản phẩm");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 430, 60));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 10));

        btnCart.setBackground(new java.awt.Color(255, 255, 255));
        btnCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Add to Shopping Basket.png")); // NOI18N
        btnCart.setText("Thêm vào giỏ");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        jPanel2.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 140, -1));

        txttensach1.setEditable(false);
        txttensach1.setBackground(new java.awt.Color(130, 195, 65));
        jPanel2.add(txttensach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 200, 30));

        tblGiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Tác giả", "Thể loại", "Năm sản xuất", "Số lượng", "Giá", "Thành tiền"
            }
        ));
        tblGiohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiohangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblGiohang);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 720, 240));

        txtsl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsl1KeyPressed(evt);
            }
        });
        jPanel2.add(txtsl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 200, 30));

        btnDeleteCart.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Shopping Basket Remove.png")); // NOI18N
        btnDeleteCart.setText("Xóa khỏi giỏ");
        btnDeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCartActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        btnbill.setBackground(new java.awt.Color(255, 255, 255));
        btnbill.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Bill.png")); // NOI18N
        btnbill.setText("Xuất hóa đơn");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        jPanel2.add(btnbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Giá");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 40, 20));

        cmbnv.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(cmbnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 190, -1));

        cmbSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã", "Tên", "Giá giảm dần", "Giá tăng dần" }));
        cmbSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSortItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 30));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Sắp xếp");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 30));

        javax.swing.GroupLayout JpnSellLayout = new javax.swing.GroupLayout(JpnSell);
        JpnSell.setLayout(JpnSellLayout);
        JpnSellLayout.setHorizontalGroup(
            JpnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnSellLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, Short.MAX_VALUE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        JpnSellLayout.setVerticalGroup(
            JpnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtab.addTab("Bán hàng", JpnSell);

        jPnHoadon.setBackground(new java.awt.Color(130, 195, 65));
        jPnHoadon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thông tin hóa đơn");
        jPnHoadon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPnHoadon.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 10, 620));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Chi tiết hóa đơn");
        jPnHoadon.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 640, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ngày lập từ");
        jPnHoadon.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mã HĐ");
        jPnHoadon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 30));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mã NV");
        jPnHoadon.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 30));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mã KH");
        jPnHoadon.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ngày lập");
        jPnHoadon.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tổng tiền");
        jPnHoadon.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        txttrangthaihd.setEditable(false);
        txttrangthaihd.setBackground(new java.awt.Color(130, 195, 65));
        txttrangthaihd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrangthaihdActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttrangthaihd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, -1));

        txtngaylap.setEditable(false);
        txtngaylap.setBackground(new java.awt.Color(130, 195, 65));
        txtngaylap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaylapActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtngaylap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, -1));

        txtmahd1.setEditable(false);
        txtmahd1.setBackground(new java.awt.Color(130, 195, 65));
        txtmahd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahd1ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtmahd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, -1));

        txtmanv.setEditable(false);
        txtmanv.setBackground(new java.awt.Color(130, 195, 65));
        txtmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanvActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, -1));

        txtmakh.setEditable(false);
        txtmakh.setBackground(new java.awt.Color(130, 195, 65));
        txtmakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmakhActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtmakh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, -1));

        txttonghd.setEditable(false);
        txttonghd.setBackground(new java.awt.Color(130, 195, 65));
        txttonghd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttonghdActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttonghd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Trạng thái");
        jPnHoadon.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("đến");
        jPnHoadon.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, 30));

        txttimngay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimngay2ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttimngay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, 30));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Giá từ");
        jPnHoadon.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        txttimgia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimgia1ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttimgia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, 30));

        txttimgia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimgia2ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttimgia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 30));

        txttimngay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimngay1ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttimngay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, 30));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("đến");
        jPnHoadon.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 30));

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã HĐ", "Ngày lập", "Giá"
            }
        ));
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblhoadon);
        if (tblhoadon.getColumnModel().getColumnCount() > 0) {
            tblhoadon.getColumnModel().getColumn(0).setMinWidth(30);
            tblhoadon.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblhoadon.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPnHoadon.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 320, 290));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mã HĐ");
        jPnHoadon.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 60, 30));

        txtmahd2.setEditable(false);
        txtmahd2.setBackground(new java.awt.Color(130, 195, 65));
        txtmahd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahd2ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtmahd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 380, -1));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sản phẩm");
        jPnHoadon.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 30));

        txttensach2.setEditable(false);
        txttensach2.setBackground(new java.awt.Color(130, 195, 65));
        txttensach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttensach2ActionPerformed(evt);
            }
        });
        jPnHoadon.add(txttensach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 380, -1));

        jLabel25.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Số lượng");
        jPnHoadon.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 90, 30));

        txtsl.setEditable(false);
        txtsl.setBackground(new java.awt.Color(130, 195, 65));
        txtsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtslActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 380, -1));

        jLabel26.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Đơn giá");
        jPnHoadon.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, 30));

        txtdongia.setEditable(false);
        txtdongia.setBackground(new java.awt.Color(130, 195, 65));
        txtdongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdongiaActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtdongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 380, -1));

        jLabel27.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Thành tiền");
        jPnHoadon.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 90, 30));

        txtthanhtien.setEditable(false);
        txtthanhtien.setBackground(new java.awt.Color(130, 195, 65));
        txtthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthanhtienActionPerformed(evt);
            }
        });
        jPnHoadon.add(txtthanhtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 380, -1));

        tblcthoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Mã sách", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblcthoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcthoadonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblcthoadon);
        if (tblcthoadon.getColumnModel().getColumnCount() > 0) {
            tblcthoadon.getColumnModel().getColumn(0).setMinWidth(30);
            tblcthoadon.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblcthoadon.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPnHoadon.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 268, 620, 340));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Refresh.png")); // NOI18N
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPnHoadon.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Search.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPnHoadon.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 40, 30));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\Search.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPnHoadon.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 40, 30));

        jtab.addTab("Hóa đơn", jPnHoadon);

        add(jtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
        xuLyLiveSearching();
    }//GEN-LAST:event_txttimActionPerformed

    private void jlbTheloaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTheloaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTheloaiMouseClicked

    private void txtmasach1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmasach1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtmasach1.setEditable(true);
            txtmasach1.setBackground(new Color(255,255,255));

        }
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            txtmasach1.setEditable(false);
            txtmasach1.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtmasach1KeyPressed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        // TODO add your handling code here:
        int row = tblSach.getSelectedRow();
        int viewRow = tblSach.getSelectedRow (); // Get the selected row in the view
int modelRow = tblSach.convertRowIndexToModel (viewRow); // Convert it to the model row
        if (row > -1) {
            String ma = tblSach.getModel().getValueAt(modelRow, 0).toString() + "";
            String Ten = tblSach.getModel().getValueAt(modelRow, 1).toString() + "";
            String tacgia = tblSach.getModel().getValueAt(modelRow, 3).toString();
          //  String tacgia = tgbus.getTenTacGia(matacgia);
            String loai = tblSach.getValueAt(row, 3).toString();
            String namsanxuat = tblSach.getValueAt(row, 4) + "";
            String soluong = tblSach.getValueAt(row, 5) + "";
            String anh = tblSach.getModel().getValueAt(modelRow, 6).toString() + "";
            String gia = tblSach.getModel().getValueAt(modelRow, 7).toString() + "";
            txtmasach1.setText(ma);
            txttensach1.setText(Ten);
            txttacgia.setText(tacgia);
            //    txttheloai.setText(loai);
            txtgia.setText(gia);
             loadAnh("image/book/"+ anh);
            int flag = 0;
           
        }
    }//GEN-LAST:event_tblSachMouseClicked

    private void loadAnh(String anh) {
        lbanh.setIcon(getAnhSach(anh));
    }
  File fileAnhSach;
    private ImageIcon getAnhSach(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        BufferedImage img = null;
        File fileImg = new File(src);
        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/book" + src);
        }
        try {
            img = ImageIO.read(fileImg);
            fileAnhSach = new File(src);

        } catch (IOException e) {

        }
        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);

        }
        return null;

    }
    private void txttrangthaihdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrangthaihdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrangthaihdActionPerformed

    private void txtngaylapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaylapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaylapActionPerformed

    private void txtmahd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahd1ActionPerformed

    private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanvActionPerformed

    private void txtmakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmakhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmakhActionPerformed

    private void txttonghdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttonghdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttonghdActionPerformed

    private void txttimngay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimngay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimngay2ActionPerformed

    private void txttimgia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimgia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimgia1ActionPerformed

    private void txttimgia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimgia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimgia2ActionPerformed

    private void txttimngay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimngay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimngay1ActionPerformed

    private void txtmahd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahd2ActionPerformed

    private void txttensach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttensach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttensach2ActionPerformed

    private void txtslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtslActionPerformed

    private void txtdongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdongiaActionPerformed

    private void txtthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthanhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthanhtienActionPerformed

    private void txtmasach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmasach1ActionPerformed

    private void tblGiohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiohangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGiohangMouseClicked
DefaultTableModel dtmcart = new DefaultTableModel();
ArrayList<sachDTO> cartlist = new ArrayList<sachDTO>();
ArrayList<CTHoaDon> cthd = new ArrayList();
    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        //button thêm vào giỏ
       if(tblSach.getSelectedRow() <0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn đầu sách.");
            return;
        }
       
       else if(txtsl1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng muốn mua");
            return;
        }else if(txtsl1.getText().trim().equals("0")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng lớn hơn 0");
            return;
        }
        double thanhtien= 0;
        sachDTO s = new sachDTO();
        CTHoaDon ct = new CTHoaDon();
        
         int row = tblSach.getSelectedRow();
         int key = Integer.parseInt(txtmasach1.getText());
         String ten = txttensach1.getText();
         String tentg = txttacgia.getText();
         int sl = Integer.parseInt(txtsl1.getText());
         int dongia = Integer.parseInt(txtgia.getText().replace(".0",""));
         
         int slconlai = Integer.parseInt(tblSach.getValueAt(row,5).toString());
         if(sl < 0 || sl>slconlai){
             JOptionPane.showMessageDialog(null, "Số lượng không đủ hoặc vượt lượng tồn kho, xin vui lòng nhập lại!");
         }else{
            
             
             
             
         for(int i = 0; i<tblGiohang.getRowCount();i++){
             int matbl = Integer.parseInt(tblGiohang.getValueAt(i, 0) + "");
             if(matbl == key){
                 int sladd = Integer.parseInt(tblGiohang.getValueAt(i,5).toString());
                 sladd +=sl;
                 tblGiohang.setValueAt(sladd, i, 5);
                 String newgia = String.valueOf(sladd*dongia);
                 tblGiohang.setValueAt(newgia, i, 7);
                 //cap nhat db
                           sach_bus.capNhatSoLuongSach(key, -sl);
                           sach_bus.doclistSach();
                           loadDataLenBangSanPham();
                           return;

             }
         }
        if (row > -1) {
            s.Ma = Integer.parseInt(tblSach.getValueAt(row, 0) + "");
            s.Ten = tblSach.getValueAt(row, 1) + "";
            s.MaTacGia = tgbus.getMafromTen(tblSach.getValueAt(row, 2).toString());
            s.MaTheLoai = theloai_bus.getMafromTen(tblSach.getValueAt(row, 3).toString());
            s.NamSanXuat =Integer.parseInt( tblSach.getValueAt(row, 4) + "");
            s.soLuong = Integer.parseInt(txtsl1.getText());
            s.Anh = tblSach.getValueAt(row, 6) + "";
            s.Gia = Double.parseDouble(tblSach.getValueAt(row, 7) + "");
            thanhtien = s.getSoLuong() * s.getGia();
            ct.setMaHD(0);
            ct.setMaSP(tgbus.getMafromTen(tblSach.getValueAt(row, 2).toString()));
            ct.setSoLuong(Integer.parseInt(txtsl1.getText()));
            ct.setDonGia(Double.parseDouble(tblSach.getValueAt(row, 7).toString()));
            ct.setThanhTien(ct.getDonGia() * ct.getSoLuong());
            
        }
       
     
        cartlist.add(s);
        

         Vector vec = new Vector();
            vec.add(s.getMa());
            vec.add(s.getTen());
            vec.add(tgbus.getTentg(s.getMaTacGia()));
            vec.add(theloai_bus.getTenloai(s.getMaTheLoai()));
            vec.add(s.getNamSanXuat());
            vec.add(s.getSoLuong());
         //   vec.add(s.getAnh());
            vec.add(s.getGia());
            vec.add(thanhtien);
            
       
       // tblGiohang.setModel(dtmcart);
          sach_bus.capNhatSoLuongSach(key, -sl);
                           sach_bus.doclistSach();
                           loadDataLenBangSanPham();
                        dtmcart.addRow(vec);
            txtmasach1.setText("");
             txttensach1.setText("");
             txttacgia.setText("");
             txtsl1.setText("0");
             txtgia.setText("");
         }
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
        if(cmbnv.getSelectedItem().toString().equalsIgnoreCase("0 - chọn nhân viên")){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn nhân viên phụ trách hóa đơn");
            return;
        }
        if(cartlist.size() <= 0){
            JOptionPane.showMessageDialog(null,"Giỏ hàng trống, không thể tạo hóa đơn");
            return;
        }else{
        int tong = 0;
        for(sachDTO s : cartlist){
        tong += s.getGia()*s.getSoLuong();
    }
        EmployeeBUS ebus = new EmployeeBUS();
        EmployeeDTO e = new EmployeeDTO();
        e = ebus.getMafromTen(cmbnv.getSelectedItem().toString());
        String name = e.ho + " " + e.ten;
       XuatHoaDonGUI xuathd = new XuatHoaDonGUI(cartlist,tong,name);
       xuathd.setVisible(true);
        xuathd.setSize(611,648);
        }
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCartActionPerformed
        // TODO add your handling code here:
        int row= tblGiohang.getSelectedRow();
        if (row<0){
            JOptionPane.showMessageDialog(null,"Giỏ hàng trống");
            return;
        }
        if(row>-1){
            int ma = Integer.parseInt(tblGiohang.getValueAt(row, 0).toString());
            int sl = Integer.parseInt(tblGiohang.getValueAt(row,5).toString());
            sach_bus.capNhatSoLuongSach(ma,sl);
            loadDataLenBangSanPham();
            dtmcart.removeRow(row);
            cartlist.remove(row);
        }
    }//GEN-LAST:event_btnDeleteCartActionPerformed

    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
        // TODO add your handling code here:
        ArrayList<HoaDon> dssp = hdbus.getListHoaDon();
               int row = tblhoadon.getSelectedRow();
        if (row < 0) {
            return;
        }
        String maHD = tblhoadon.getValueAt(row, 0) + "";
        HoaDon pn = hdbus.getHoaDon(maHD);
        int i = tblhoadon.getSelectedRow();
        HoaDon hd = new HoaDon();
        for(HoaDon h : dssp){
            if(Integer.parseInt(tblhoadon.getValueAt(i,0).toString()) == h.getMaHD()){
                hd = h;
            }
        }
        txtmahd1.setText(String.valueOf(hd.getMaHD()));
        txtmanv.setText(String.valueOf(hd.getMaNV()));
        txtmakh.setText(String.valueOf(hd.getMaKH()));
        txtngaylap.setText(hd.getNgayLap().toString());
        txttonghd.setText(String.valueOf(hd.getTongTien()));
        txttrangthaihd.setText(hd.getGhiChu());
        loadDataTableCTHoaDon(maHD);
    }//GEN-LAST:event_tblhoadonMouseClicked

    private void cmbSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSortItemStateChanged
        // TODO add your handling code here:
        if(cmbSort.getSelectedItem() == "Mã"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblSach.getModel());
            tblSach.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblSach.getColumn("Mã").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }else if(cmbSort.getSelectedItem() == "Tên"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblSach.getModel());
            tblSach.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblSach.getColumn("Tên").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        if(cmbSort.getSelectedItem() == "Giá tăng dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblSach.getModel());
            tblSach.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblSach.getColumn("Giá").getModelIndex(), SortOrder.ASCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }else if(cmbSort.getSelectedItem() == "Giá giảm dần"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>((TableModel)tblSach.getModel());
            tblSach.setRowSorter(sorter);

            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
            sortKeys.add(new RowSorter.SortKey(tblSach.getColumn("Giá").getModelIndex(), SortOrder.DESCENDING));
            //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
       
       
    }//GEN-LAST:event_cmbSortItemStateChanged

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        loadDataHoaDon();
        loadDatacthd();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblcthoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcthoadonMouseClicked
        // TODO add your handling code here:
        int i = tblcthoadon.getSelectedRow();
        txtmahd2.setText(tblcthoadon.getValueAt(i, 0).toString());
        txttensach2.setText(tblcthoadon.getValueAt(i, 1).toString());
        txtsl.setText(tblcthoadon.getValueAt(i, 2).toString());
        txtdongia.setText(tblcthoadon.getValueAt(i, 3).toString());
        txtthanhtien.setText(tblcthoadon.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tblcthoadonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                dtmhd.setRowCount(0);

        ArrayList<HoaDon> dssp = hdbus.getListHoaDonTheoGia(txttimgia1.getText(), txttimgia2.getText());

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (HoaDon sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaHD());
            //vec.add(sp.getMaNV());
            //vec.add(sp.getMaKH());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            //vec.add(sp.getGhiChu());

            dtmhd.addRow(vec);
     
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        dtmhd.setRowCount(0);

        ArrayList<HoaDon> dssp = hdbus.getListHoaDonTheoNgay(txttimngay1.getText(), txttimngay2.getText());

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (HoaDon sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMaHD());
            //vec.add(sp.getMaNV());
            //vec.add(sp.getMaKH());
            vec.add(sp.getNgayLap());
            vec.add(sp.getTongTien());
            //vec.add(sp.getGhiChu());

            dtmhd.addRow(vec);
     
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsl1KeyPressed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_txtsl1KeyPressed

    DefaultTableModel dtmsearch = new DefaultTableModel();
 private void loadDataLenBangSanPham( ArrayList<sachDTO> dssp) {
        // sach_bus.doclistSach();
        dtmsearch.setRowCount(0);

       // ArrayList<sachDTO> dssp = sach_bus.getListSach();

        DecimalFormat dcf = new DecimalFormat("###,###");

        for (sachDTO sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMa());
            vec.add(sp.getTen());
            vec.add(sp.getMaTacGia());
            vec.add(sp.getMaTheLoai());
            vec.add(sp.getNamSanXuat());
            vec.add(sp.getSoLuong());
            vec.add(sp.getAnh());
            vec.add(sp.getGia());

            dtmsearch.addRow(vec);

        }
    }
    private void xuLyLiveSearching()
    {
        ArrayList<sachDTO> dsSach = sach_bus.timlKiemSachLive(txttim.getText());
        loadDataLenBangSanPham(dsSach);
    }
    public void searchLive()
    {
        txttim.getDocument().addDocumentListener(new DocumentListener()
        {
              @Override
            public void insertUpdate(DocumentEvent e) {
               xuLyLiveSearching();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                xuLyLiveSearching();
            }   
                
                
                
        } );
    }
    public void loadDataCmbNV(){
        cmbnv.removeAll();
        EmployeeBUS tgbus = new EmployeeBUS();
        ArrayList<EmployeeDTO> tacgiaList = tgbus.getdsnv();

        cmbnv.addItem("0 - Chọn nhân viên ");

        for (EmployeeDTO DataBox : tacgiaList) {
            cmbnv.addItem(DataBox.getho() + " " + DataBox.getten());
        }
    }
     private void loadDataTableCTHoaDon(String maPN) {
        dtmcthd.setRowCount(0);
        ArrayList<CTHoaDon> dsct = cthdbus.getListCTHoaDonTheoMaHD(maPN);
        if (dsct != null) {
            for (CTHoaDon ct : dsct) {
                Vector vec = new Vector();
                vec.add(maPN);
                vec.add(ct.getMaSP());
                vec.add((ct.getSoLuong()));
                vec.add((ct.getDonGia()));
                vec.add((ct.getThanhTien()));
                dtmcthd.addRow(vec);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JpnSell;
    public javax.swing.JButton btnCart;
    public javax.swing.JButton btnDeleteCart;
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnbill;
    public javax.swing.JComboBox cmbSort;
    public javax.swing.JComboBox cmbnv;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPnHoadon;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel jlbTheloai;
    public javax.swing.JTabbedPane jtab;
    public javax.swing.JLabel lbanh;
    public javax.swing.JTable tblGiohang;
    public javax.swing.JTable tblSach;
    public javax.swing.JTable tblcthoadon;
    public javax.swing.JTable tblhoadon;
    public javax.swing.JTextField txtdongia;
    public javax.swing.JTextField txtgia;
    public javax.swing.JTextField txtmahd1;
    public javax.swing.JTextField txtmahd2;
    public javax.swing.JTextField txtmakh;
    public javax.swing.JTextField txtmanv;
    public javax.swing.JTextField txtmasach1;
    public javax.swing.JTextField txtngaylap;
    public javax.swing.JTextField txtsl;
    public javax.swing.JTextField txtsl1;
    public javax.swing.JTextField txttacgia;
    public javax.swing.JTextField txttensach1;
    public javax.swing.JTextField txttensach2;
    public javax.swing.JTextField txtthanhtien;
    public javax.swing.JTextField txttim;
    public javax.swing.JTextField txttimgia1;
    public javax.swing.JTextField txttimgia2;
    public javax.swing.JTextField txttimngay1;
    public javax.swing.JTextField txttimngay2;
    public javax.swing.JTextField txttonghd;
    public javax.swing.JTextField txttrangthaihd;
    // End of variables declaration//GEN-END:variables
}
