/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.PhanQuyenBUS;
import DTO.PhanQuyenDTO;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import Others.Controller;
import Others.category;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {
        DefaultTableModel model = new DefaultTableModel();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Connection con = null;
        
                List<category> cate = new ArrayList();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("image\\icon.png"));
        setTitle("Quản lý nhà sách");
        JPnContent.setSize(1100,700);
        Controller controller = new Controller(JPnContent);
        controller.setView(JPnHome);
        JPnBooks.setVisible(false);
        JPnCustomer.setVisible(false);
        JPnEmployee.setVisible(false);
        JPnImport.setVisible(false);
        JPnAnalyze.setVisible(false);

         cate.add(new category("Bán hàng",JPnService));
         cate.add(new category("Khuyến mãi",JPnVoucher));
         cate.add(new category("Default",JPnHome));
//         cate.add(new category("Nhap",JPnStorage));
                 addcontrols();

         controller.setEvent(cate);
        
         

    }
    public void addcontrols(){
            PhanQuyenDTO quyen = PhanQuyenBUS.quyenTK;
            if(quyen.getQlSanPham() ==1){
                 cate.add(new category("Sách",JPnBooks));
                 JPnBooks.setVisible(true);
      }
            if(quyen.getQlKhachHang() ==1){
                cate.add(new category("Khách hàng",JPnCustomer));
                                 JPnCustomer.setVisible(true);
                               // Point p= JPnCustomer.getLocationOnScreen();
                                //p.y -=120;
                                JPnCustomer.setLocation(0,230);

            }
            if(quyen.getQlNhanVien() ==1){
                         cate.add(new category("Nhân viên",JPnEmployee));
                                          JPnEmployee.setVisible(true);

            }
            if(quyen.getNhapHang() ==1){
                   cate.add(new category("Nhập hàng",JPnImport));
                                    JPnImport.setVisible(true);

            }
            if(quyen.getThongKe()==1){
                         cate.add(new category("Thống kê",JPnAnalyze));
                 JPnAnalyze.setVisible(true);

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnStat = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        Sidebar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JPnHome = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpnCate = new javax.swing.JPanel();
        JPnService = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblSearch = new javax.swing.JLabel();
        JPnVoucher = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LblSearch1 = new javax.swing.JLabel();
        JPnBooks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LblBooks = new javax.swing.JLabel();
        JPnEmployee = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        LblEmployee = new javax.swing.JLabel();
        JPnCustomer = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        LblEmployee2 = new javax.swing.JLabel();
        JPnImport = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        LblEmployee1 = new javax.swing.JLabel();
        JPnAnalyze = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LblAnalyze = new javax.swing.JLabel();
        JPnContent = new javax.swing.JPanel();

        JPnStat.setBackground(new java.awt.Color(43, 152, 54));
        JPnStat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(73, 175, 22));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số lượng đang mượn");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        JPnStat.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 210, 112));

        jPanel4.setBackground(new java.awt.Color(139, 202, 132));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 112));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số lượng độc giả");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 200, -1));

        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        JPnStat.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        jPanel5.setBackground(new java.awt.Color(101, 209, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số lượng sách");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 230, -1));

        JPnStat.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, 112));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(105, 107, 109));
        setPreferredSize(new java.awt.Dimension(1400, 700));
        setSize(new java.awt.Dimension(1400, 700));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Sidebar.setBackground(new java.awt.Color(130, 195, 65));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 10));

        JPnHome.setBackground(new java.awt.Color(130, 195, 65));
        JPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(130, 195, 65));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\nvc (1).jpg")); // NOI18N
        JPnHome.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 120));

        Sidebar.add(JPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpnCate.setBackground(new java.awt.Color(130, 195, 65));
        jpnCate.setLayout(new javax.swing.BoxLayout(jpnCate, javax.swing.BoxLayout.Y_AXIS));

        JPnService.setBackground(new java.awt.Color(255, 255, 255));
        JPnService.setBorder(null);
        JPnService.setAutoscrolls(true);
        JPnService.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnService.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnService.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\sell.png")); // NOI18N
        jLabel2.setText("jLabel1");
        JPnService.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblSearch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LblSearch.setText("Bán hàng");
        JPnService.add(LblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        jpnCate.add(JPnService);

        JPnVoucher.setBackground(new java.awt.Color(255, 255, 255));
        JPnVoucher.setBorder(null);
        JPnVoucher.setAutoscrolls(true);
        JPnVoucher.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnVoucher.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnVoucher.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnVoucher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\voucher.png")); // NOI18N
        jLabel4.setText("jLabel1");
        JPnVoucher.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblSearch1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LblSearch1.setText("Khuyến mãi");
        JPnVoucher.add(LblSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 120, -1));

        jpnCate.add(JPnVoucher);

        JPnBooks.setBackground(new java.awt.Color(255, 255, 255));
        JPnBooks.setToolTipText("");
        JPnBooks.setAutoscrolls(true);
        JPnBooks.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnBooks.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnBooks.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\book (1).png")); // NOI18N
        jLabel3.setText("jLabel1");
        JPnBooks.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblBooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblBooks.setText("Sách");
        JPnBooks.add(LblBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        jpnCate.add(JPnBooks);

        JPnEmployee.setBackground(new java.awt.Color(255, 255, 255));
        JPnEmployee.setAutoscrolls(true);
        JPnEmployee.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnEmployee.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnEmployee.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\employees.png")); // NOI18N
        jLabel12.setText("jLabel1");
        JPnEmployee.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 50));

        LblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblEmployee.setText("Nhân viên");
        JPnEmployee.add(LblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        jpnCate.add(JPnEmployee);

        JPnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        JPnCustomer.setAutoscrolls(true);
        JPnCustomer.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnCustomer.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnCustomer.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\customer.png")); // NOI18N
        jLabel15.setText("jLabel1");
        JPnCustomer.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 50));

        LblEmployee2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblEmployee2.setText("Khách hàng");
        JPnCustomer.add(LblEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 110, -1));

        jpnCate.add(JPnCustomer);

        JPnImport.setBackground(new java.awt.Color(255, 255, 255));
        JPnImport.setAutoscrolls(true);
        JPnImport.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnImport.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnImport.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnImport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\import.png")); // NOI18N
        jLabel13.setText("jLabel1");
        JPnImport.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 50));

        LblEmployee1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblEmployee1.setText("Nhập hàng");
        JPnImport.add(LblEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 110, -1));

        jpnCate.add(JPnImport);

        JPnAnalyze.setBackground(new java.awt.Color(255, 255, 255));
        JPnAnalyze.setAutoscrolls(true);
        JPnAnalyze.setMaximumSize(new java.awt.Dimension(320, 75));
        JPnAnalyze.setMinimumSize(new java.awt.Dimension(320, 50));
        JPnAnalyze.setPreferredSize(new java.awt.Dimension(320, 50));
        JPnAnalyze.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\Java\\ql_nhasach\\image\\icons\\analyzing.png")); // NOI18N
        jLabel9.setText("jLabel1");
        JPnAnalyze.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblAnalyze.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblAnalyze.setText("Thống kê");
        JPnAnalyze.add(LblAnalyze, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 150, -1));

        jpnCate.add(JPnAnalyze);

        Sidebar.add(jpnCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 320, 580));

        JPnContent.setBackground(new java.awt.Color(130, 195, 65));
        JPnContent.setPreferredSize(new java.awt.Dimension(1050, 700));

        javax.swing.GroupLayout JPnContentLayout = new javax.swing.GroupLayout(JPnContent);
        JPnContent.setLayout(JPnContentLayout);
        JPnContentLayout.setHorizontalGroup(
            JPnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        JPnContentLayout.setVerticalGroup(
            JPnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(368, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1056, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,0,0));
    }
    void setColor(Panel panel){
        panel.setBackground(new Color(0,0,0));
    }
    
    void ResetColor(Panel panel){
        panel.setBackground(new Color(105,107,109));
    }
    void ResetColor(JPanel panel){
        panel.setBackground(new Color(105,107,109));
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaiKhoanGUI login = new TaiKhoanGUI();
                login.showWindow();
 //               new Menu().setVisible(true);
            }
        });
    }
        public void showWindow() {
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
                Image icon = Toolkit.getDefaultToolkit().getImage("image\\icon.png");
        this.setIconImage(icon);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnAnalyze;
    private javax.swing.JPanel JPnBooks;
    private javax.swing.JPanel JPnContent;
    private javax.swing.JPanel JPnCustomer;
    private javax.swing.JPanel JPnEmployee;
    private javax.swing.JPanel JPnHome;
    private javax.swing.JPanel JPnImport;
    private javax.swing.JPanel JPnService;
    private javax.swing.JPanel JPnStat;
    private javax.swing.JPanel JPnVoucher;
    private javax.swing.JLabel LblAnalyze;
    private javax.swing.JLabel LblBooks;
    private javax.swing.JLabel LblEmployee;
    private javax.swing.JLabel LblEmployee1;
    private javax.swing.JLabel LblEmployee2;
    private javax.swing.JLabel LblSearch;
    private javax.swing.JLabel LblSearch1;
    private javax.swing.JPanel Sidebar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpnCate;
    // End of variables declaration//GEN-END:variables
}
